### ISSUE TITLE
Support EOCloud data provider

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#1]
**[Original report](https://bitbucket.org/geostorm/eodag/issue/1) by Mickaël Savinaud (Bitbucket: [savmickael](https://bitbucket.org/savmickael), GitHub: [savmickael](https://github.com/savmickael)).**

----------------------------------------

Some information are here: https://eocloud.cloudferro.com/knowledgebase.php?action=displayarticle&id=66

**Comment by sbrunato** [comment]
@savmickael https://eocloud.cloudferro.com now redirects to https://cloudferro.com/en/eo-cloud/cloud-for-earth-observation/ which lists 3 providers:
- Creodias, already implemented
- Wekeo, support request already existing: https://github.com/CS-SI/eodag/issues/57
- CODE-DE,  support request already existing: https://github.com/CS-SI/eodag/issues/6

It seems like CloudFerro EOCloud provider is not available any more, or has been merged with another project. Can you confirm this ?

**Comment by savmickael** [comment]
eocloud is the creodias interface so you can close this issue.



Le jeu. 29 avr. 2021 à 18:59, Sylvain Brunato ***@***.***> a
écrit :
