### ISSUE TITLE
Scenes search: start/end as date vs datetime

### ISSUE THREAD

**Issue by MatteaE** [CS-SI/eodag#1035]
As of version 2.12, it looks like the date bounds for a scene search are always treated as datetimes, for example a value of 2020-01-01 is treated as 2020-01-01 00:00:00.
This is formally correct but might lead to unexpected missing scenes, because (when specifying just dates and not datetimes) the interval is closed on the left but open on the right (start day is included in the search, end day is excluded).

It would be great if this could either be prominently stated in the documentation, or possibly automatically taken care of (make the interval closed on both sides by treating the end day as a datetime with 23:59:59.999 time).

Thanks a lot!

**Comment by sbrunato** [comment]
Hello @MatteaE and thanks for the suggestion to add this behavior in the documentation
