### ISSUE TITLE
Abandonned dependency cause eodag to not work correctly on python 3.13

### ISSUE THREAD

**Issue by mariusvn** [CS-SI/eodag#1036]
**Describe the bug**
the dependency to request-ftp cause an `import cgi` which does not exists anymore on python 3.13

**Code To Reproduce**
Just execute any code inspector, at least in 3.11 with `pytest` I get a warning when i use eodag because it import the package `cgi` which is deprecated and removed in 3.13

**Output**
```
 C:\Users\...\venv\Lib\site-packages\requests_ftp\ftp.py:9: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
    import cgi
```

**Environment:**
 - Python version: `3.11`
 - EODAG version: `2.11.0`

**Comment by mariusvn** [comment]
its not really a bug but just an issue to make you know that changes may be needed in 3.13

**Comment by sbrunato** [comment]
Hello @mariusvn and thanks for the information. We should remove this "abandoned" dependency and use `urllib` instead, or find another alternative
