### ISSUE TITLE
[server] type missing on some queryables

### ISSUE THREAD

**Issue by alambare-csgroup** [CS-SI/eodag#1040]
**Describe the bug**
The type of some queryables are incorrect.

**Code To Reproduce**
CLI commands or Python code snippet to reproduce the bug. Please use maximum verbosity using:
```sh
eodag -vvv [OPTIONS] COMMAND [ARGS]...
```
or
```py
eodag serve-rest

curl http://localhost:5000/collections/S2_MSI_L2A/queryables?provider=creodias
```

**Output**
```json
...
"eo:cloud_cover": {
    "description": "eo:cloud_cover",
    "$ref": null,
    "type": [
        "null"
    ],
    "enum": null,
    "value": null
},
"eo:snow_cover": {
    "description": "eo:snow_cover",
    "$ref": null,
    "type": [
        "null"
    ],
    "enum": null,
    "value": null
}
...
```

**Additional context**
`python_type_to_json` skips `typing.Annotated` type. So queryables that have a `Union` type containing a `typing.Annotated` type get dropped

**Comment by sbrunato** [comment]
Please inspire from https://planetarycomputer.microsoft.com/api/stac/v1/collections/sentinel-2-l2a/queryables:
- use schema if exists (https://stac-extensions.github.io/eo/v1.0.0/schema.json#/definitions/fields/properties/eo:cloud_cover)
- use additional fields:
```json
"type": "number",
"minimum": 0,
"maximum": 100,
```
