### ISSUE TITLE
asynchronous download_all

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#120]
**[Original report](https://bitbucket.org/geostorm/eodag/issue/120) by me.**

----------------------------------------

Provide the way to download products asynchronously and in parallel for better performances on long products lists

**Comment by iliion** [comment]
Is multithreadind implemented in any way? I cannot find any documentation about it (except this post)

**Comment by sbrunato** [comment]
Hello @iliion , no this is not implemented yet. See https://github.com/CS-SI/eodag/issues/146#issuecomment-799302847 (this issue was closed as duplicate)
