### ISSUE TITLE
Support geodes provider

### ISSUE THREAD

**Issue by savmickael** [CS-SI/eodag#1216]
Support geodes provider : https://geodes.cnes.fr/migration-de-peps-vers-geodes/ 

Deprecate peps provider
Add geodes provider

**Comment by sbrunato** [comment]
Hello @savmickael , the support of this new provider is planned, we'll keep you informed when it is done.

Related to https://github.com/CS-SI/eodag/discussions/1184

**Comment by aaiche-meoss** [comment]
Hello @sbrunato, PEPS wouldn't be available from October. 
Unless I'm mistaken, I see that you haven't yet updated the eodag tool. Could we know when it woud be updated? Thank you.

**Comment by sbrunato** [comment]
Hello @aaiche-meoss , work is in progress and `geodes` provider should be available when `peps` service stops
