### ISSUE TITLE
Document config parameters in plugins

### ISSUE THREAD

**Issue by alambare** [CS-SI/eodag#1286]
**Is your feature request related to a problem? Please describe.**
Add docstring documentation for config parameters available in each plugin.

**Describe the solution you'd like**
Use docstring to document the parameters available for each plugin.
Should be described for each parameter:
- the parameter name
- a description explaining what is it for, what does it do
- format and type of expected value
- whether it is optional or mandatory
- default value

plugins to cover:

**Api**

- [x] EcmwfApi
- [x] UsgsApi

**Authentication**

- [x] AwsAuth
- [x] GenericAuth
- [x] HTTPHeaderAuth
- [x] KeycloakOIDCPasswordAuth
- [x] OAuth
- [x] OIDCRefreshTokenBase
- [x] OIDCAuthorizationCodeFlowAuth
- [x] HttpQueryStringAuth
- [x] QueryStringAuth
- [x] RequestsSASAuth
- [x] SASAuth
- [x] TokenAuth
- [x] OIDCTokenExchangeAuth

**Crunch**

- [x] FilterDate
- [x] FilterLatestIntersect
- [x] FilterLatestByName
- [x] FilterOverlap
- [x] FilterProperty

**Download**

- [x] AwsDownload
- [x] CreodiasS3Download
- [x] HTTPDownload
- [x] S3RestDownload

**Search**

- [x] BuildPostSearchResult
- [x] BuildSearchResult
- [x] CopMarineSearch
- [x] CreodiasS3Search
- [x] CSWSearch
- [x] DataRequestSearch
- [x] QueryStringSearch
- [x] ODataV4Search
- [x] PostJsonSearch
- [x] StacSearch
- [x] StaticStacSearch

**Comment by jlahovnik** [comment]
> **Is your feature request related to a problem? Please describe.** Add docstring documentation for config parameters available in each plugin.
> 
> **Describe the solution you'd like** Use docstring to document the parameters available for each plugin. Should be described for each parameter:
> 
>     * the parameter name
> 
>     * a description explaining what is it for, what does it do
> 
>     * format and type of expected value
> 
>     * whether it is optional or mandatory
> 
>     * default value
> 
> 
> plugins to cover:
> 
> **Api**
> 
>     * [x]  EcmwfApi
> 
>     * [x]  UsgsApi
> 
> 
> **Authentication**
> 
>     * [x]  AwsAuth
> 
>     * [x]  GenericAuth
> 
>     * [x]  HTTPHeaderAuth
> 
>     * [x]  KeycloakOIDCPasswordAuth
> 
>     * [x]  OAuth
> 
>     * [x]  OIDCRefreshTokenBase
> 
>     * [x]  OIDCAuthorizationCodeFlowAuth
> 
>     * [x]  HttpQueryStringAuth
> 
>     * [x]  QueryStringAuth
> 
>     * [x]  RequestsSASAuth
> 
>     * [x]  SASAuth
> 
>     * [x]  TokenAuth
> 
>     * [x]  OIDCTokenExchangeAuth
> 
> 
> **Crunch**
> 
>     * [x]  FilterDate
> 
>     * [x]  FilterLatestIntersect
> 
>     * [x]  FilterLatestByName
> 
>     * [x]  FilterOverlap
> 
>     * [x]  FilterProperty
> 
> 
> **Download**
> 
>     * [x]  AwsDownload
> 
>     * [x]  CreodiasS3Download
> 
>     * [x]  HTTPDownload
> 
>     * [x]  S3RestDownload
> 
> 
> **Search**
> 
>     * [x]  BuildPostSearchResult
> 
>     * [x]  BuildSearchResult
> 
>     * [x]  CopMarineSearch
> 
>     * [x]  CreodiasS3Search
> 
>     * [x]  CSWSearch
> 
>     * [x]  DataRequestSearch
> 
>     * [x]  QueryStringSearch
> 
>     * [x]  ODataV4Search
> 
>     * [x]  PostJsonSearch
> 
>     * [x]  StacSearch
> 
>     * [x]  StaticStacSearch

NOTE: RequestsSASAuth and QueryStringAuth aren't plugins and therefore don't have a config
