### ISSUE TITLE
tests failing due to issues with shapely and python 3.12

### ISSUE THREAD

**Issue by jlahovnik** [CS-SI/eodag#1302]
If python 3.12 is used, during the python 3.12 test run several tests are failing due to an error in the shapely library, see for example this failed run: [test run](https://github.com/CS-SI/eodag/actions/runs/10451170765/job/28937016614?pr=1298)

There are 2 possible solutions:

- downgrade numpy to 2.0.1 to ensure compatibility with the current shapely version
- wait for shapely 2.0.6 (containing this [PR](https://github.com/shapely/shapely/pull/2099) which should fix the issue) to be released and upgrade to this version

**Environment:**
 - Python version: 3.12

**Additional context**
Add any other context about the bug here.

**Comment by EwoutH** [comment]
Shapely 2.0.6 is now released, which resolved the issue with NumPy 2.1.0.

**Comment by jlahovnik** [comment]
pull request created to enforce the use of shapely 2.0.6
