### ISSUE TITLE
Enable other  area relations than "intersects"

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#137]
Hello,

Usually, the given area relations allowed to be used in a query are `{intersects, contains, is-within}`. They are used with a given AOI.

For now, only the `intersects` one is used (for compatibility issues I assume). 
However, I would really use an option to enable other area relations.

Could it be done by adding a simplified crunching plugin than filter_overlap ?
With this one I understand that I can recreate the effect of the `contains` area relation by setting a 100% overlap, but I cannot recreate the `is-within`. (am I missing sth ?)

Thanks a lot

**Comment by sbrunato** [comment]
Hello Rémi, and thank you for this feature request. We will also try to add these crunchers and give you a feedback
