### ISSUE TITLE
[S2/Landsats] Allow the query by tiles

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#139]
Hello,

A nice feature would be tu allow the user to query by tile, or if too specific to S2/Landsats products, to allow the user to query data from its title with a regex, fore example `"*T32ULU*" in title` would be enough for this kind of query.

I know that this workaround works for scihub: `keywords['raw'] = 'filename:*_T32ULU_*'`

Best Regards,

Rémi BRAUN

**Comment by sbrunato** [comment]
Hello Rémi, and thank you for this feature request. We will check if this can be integrated

**Comment by sbrunato** [comment]
Hello Remi, query by S2 tiles is now possible. An example has been added to the "search_area" tutorial https://github.com/CS-SI/eodag/blob/master/examples/tuto_search_area.ipynb

**Comment by remi-braun** [comment]
Perfect !
I will test this as soon as possible.
I'm very excited, it sounds really promissing :)
