### ISSUE TITLE
Small errors in serializing/deserializing

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#140]
Hello,

I noticed that there are small errors in serializing and deserializing EoProduct.  
They sadly prevent `EOProduct == deserialize(serialize(EOProduct))`. 

I've traced those errors to these functions in `_product.py`:
- `as_dict`: Some fields are forgotten, such as `downloader`,  `downloader_auth`, `search_args`, `search_kwargs`. They could be managed the same way as `provider` for example.
- `from_geojson`: The fields beginning by `eodag_` should be popped in order to make them disappear from EOProduct's properties.

Best Regards,

Rémi

**Comment by sbrunato** [comment]
Hello Rémi, thank you for the feedback and for tracing the errors. We will check what goes wrong and fix it as soon as possible

**Comment by sbrunato** [comment]
An example of serialization/deserialization is provided in https://eodag.readthedocs.io/en/latest/tutorials/tuto_advanced.html

As eodag plugin and auth information are not stored in the geojson, you should use [`EOProduct.register_downloader()`](https://eodag.readthedocs.io/en/latest/api.html#eodag.api.product._product.EOProduct.register_downloader) method after loading a product with `EOProduct.from_geojson()`:
```python
from eodag import EODataAccessGateway
from eodag.api.product import EOProduct

dag = EODataAccessGateway()
dags_L1C, _ = dag.search(
    productType='S2_MSI_L1C', 
    box={
        'lonmin': 1.23,
        'lonmax': 1.68,
        'latmin': 43.42,
        'latmax': 43.76
    }, 
    start='2020-06-01', end='2020-06-15',
)
prod = dags_L1C[0]
downloader, authenticator = prod.downloader, prod.downloader_auth
prod_dict = prod.as_dict()

new_prod = EOProduct.from_geojson(prod_dict)
new_prod.register_downloader(downloader, authenticator)

```

**Comment by remi-braun** [comment]
Thanks for the link :)

But I was wondering if the point of serializing/deserializing isn't to retrieve the exact same product after than before ?
I my case I convert your *SearchList* in a *GeoPandas Dataframe* to cruch some things and I need to be able to convert the *Dataframe* back to the original *SearchList*.

I coded a worekaround that seems to work fine in my case, but I fear it wont last long with the upcomiong evolutions of EODag.

Maybe I was mistaken about the goal of these functions, but I understood it this way.

**Comment by sbrunato** [comment]
You are right in the point of serializing/deserializing.
The mechanism should be simpler and the user should not need to call `register_downloader()` manually.  
We will see if we can call it internally when executing the `download()` method.
Thanks for this proposal!

**Comment by remi-braun** [comment]
FYI, my (not very pretty) workaround:
```python
# WORKAROUND
def eoproduct_from_geojson(feature: dict) -> EOProduct:
    """Builds an :class:`~eodag.api.product.EOProduct` object from its
    representation as geojson

    :param feature: The representation of a :class:`~eodag.api.product.EOProduct`
                    as a Python dict
    :type feature: dict
    :returns: An instance of :class:`~eodag.api.product.EOProduct`
    :rtype: :class:`~eodag.api.product.EOProduct`
    """
    properties = feature

    # Pop useless fields
    provider = properties.pop("eodag_provider")
    driver = properties.pop("eodag_driver")
    downloader = properties.pop("eodag_downloader")
    downloader_auth = properties.pop("eodag_downloader_auth")
    search_args = properties.pop("eodag_search_args")
    search_kwargs = properties.pop("eodag_search_kwargs")
    product_type = properties.pop("eodag_product_type")
    search_intersection = geometry.shape(properties.pop("eodag_search_intersection"))

    obj = EOProduct(provider, properties, productType=product_type)
    obj.search_intersection = search_intersection

    # WORKAROUND
    obj.driver = driver
    obj.downloader = downloader
    obj.downloader_auth = downloader_auth
    obj.search_args = search_args
    obj.search_kwargs = search_kwargs

    return obj


# WORKAROUND
def eoproduct_to_geojson(prod: EOProduct) -> dict:
    """
    Builds a representation of EOProduct as a dictionary to enable its geojson serialization

    :returns: The representation of a :class:`~eodag.api.product.EOProduct` as a
              Python dict
    :rtype: dict
    """
    search_intersection = None
    if prod.search_intersection is not None:
        search_intersection = geometry.mapping(prod.search_intersection)
    geojson_repr = {
        "type": "Feature",
        "geometry": geometry.mapping(prod.geometry),
        "id": prod.properties.get("id"),
        "properties": {
            "eodag_product_type": prod.product_type,
            "eodag_provider": prod.provider,
            "eodag_search_intersection": search_intersection,
            # WORKAROUND
            "eodag_driver": prod.driver,
            "eodag_downloader": prod.downloader,
            "eodag_downloader_auth": prod.downloader_auth,
            "eodag_search_args": prod.search_args,
            "eodag_search_kwargs": prod.search_kwargs,

        },
    }
    geojson_repr["properties"].update(
        {
            key: value
            for key, value in prod.properties.items()
            if key not in ("geometry", "id")
        }
    )
    return geojson_repr

```

**Comment by sbrunato** [comment]
Thank you, but this way the product is not really JSON serialized as you store some objects as is (driver, downloader, downloader_auth). Executing `json.dumps(geojson_repr)` won't work.
The thing that we can do is to create these objects if they do not exist before downloading them, as it is done in CLI mode.

**Comment by remi-braun** [comment]
Yes I understand, this way it cannot be saved as a file.
Maybe a pickle would do the trick ?

Or maybe serializing/deserializing on disk !=  on memory ?

I leave it to you, thanks for considering taking care of it :)
