### ISSUE TITLE
Unzipping of downloaded product as an option

### ISSUE THREAD

**Issue by koleckt** [CS-SI/eodag#145]
When downloading a product, the user should stay in ZIP format. 

Actually, the unzipping is automatic and cannot be desactivated

A special key in command line and/or config file to deactivate the unzipping could be very useful.

**Comment by sbrunato** [comment]
Thanks for your feedback, for the moment the unzipping option can be set globally per provider via:
- changing the `extract` parameter (boolean) in your configuration file;
- setting the environment variable `EODAG__MYPROVIDER__DOWNLOAD__EXTRACT` to `true|false`, before instantiating eodag;

We will also permit to set it dynamically in a future version
