### ISSUE TITLE
queryable operator other than "eq"

### ISSUE THREAD

**Issue by floriandeboissieu** [CS-SI/eodag#1456]
Many thanks for your package, always very useful for my research.

It is more a question than a feature:
is there a simple way to pass to search parameter another operator than "eq" (or the one defined in the provider config)?

Here is an example, among the things I tried but that is not working as `"identifier":{'contains':tile}` is converted to `"identifier":{"eq", {'contains':tile}}`:
```python
from eodag import EODataAccessGateway

dag = EODataAccessGateway()

search_args = {
    "productType": 'S2_MSI_L2A_MAJA',
    "start": "2016-01-01", #start_date,
    "end": '2016-01-31', #end_date,
    "provider":"geodes",
    "identifier":{'contains':'T31TGM'}
    }
search_results = dag.search_all(**search_args)
```
I tried it as an http request and it is giving the good result.

**Comment by sbrunato** [comment]
Hello @floriandeboissieu , and thanks for your kind words.
No, search operators are not flexible for the moment. Most are using `eq`, and some are using `lte`, `contains` etc. (`cloudCover` uses `lte`).  But this is defined in the provider metadata mapping and cannot be changed easily for the moment.
A feature request is already opened for it, https://github.com/CS-SI/eodag/issues/1074, so I will close this one as duplicate. 

And if you want to search for a given tile, you can use the parameter `tileIdentifier` that will be available for `geodes` in EODAG next release (see https://github.com/CS-SI/eodag/pull/1457). Before this release, you can also directly use provider-specific parameter `spaceborne:tile` (with a `T` prefix).

**Comment by floriandeboissieu** [comment]
Thanks, I'll follow issue #1074 then.
