### ISSUE TITLE
Number of products limit to 20 with dag.search and len(products) with the Python API 

### ISSUE THREAD

**Issue by BasileGoussard** [CS-SI/eodag#149]
Hi,
I'm using dag.search and trying to retrieve all the data for a specific area starting in 2018 until 2020. 
However, the request seems to be limit to 20 results. 
Do you know a way to unlock this limit?

**Code To Reproduce**

product_type = 'L8_REFLECTANCE'
extent = {
    'lonmin': -1.999512,
    'lonmax': 4.570313,
    'latmin': 42.763146,
    'latmax': 46.754917
}

products, estimated_total_nbr_of_results = (
    dag.search(
        productType=product_type,
        start='2018-01-01',
        end  ='2020-10-01',
        box  = extent,
        cloudCover=50,
    ))

print('Number of items : '  + str(len(products)))
print('\n')
pprint(products)

**Output**

Number of items : 20

[EOProduct(id=LANDSAT8-OLITIRS-XS_20200704-105423-344_L2A_T30TXQ_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200704-105423-344_L2A_T30TXP_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200704-105423-344_L2A_T30TWP_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200704-105411-401_L2A_T30TXR_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200701-102339-929_L2A_T31TFH_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200701-102327-986_L2A_T31TFJ_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200701-102316-041_L2A_T31TFK_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200701-102304-097_L2A_T31TFL_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200629-103524-832_L2A_T31TEL_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200627-104821-357_L2A_T30TXN_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200627-104809-412_L2A_T30TWP_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200627-104809-412_L2A_T30TXP_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200627-104757-470_L2A_T30TYQ_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200627-104757-470_L2A_T30TXQ_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200624-101725-846_L2A_T31TFH_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200624-101713-903_L2A_T31TFJ_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200622-102958-419_L2A_T31TEH_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200622-102958-419_L2A_T31TDH_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200622-102958-419_L2A_T31TFH_D, provider=theia),
 EOProduct(id=LANDSAT8-OLITIRS-XS_20200622-102934-534_L2A_T31TFJ_D, provider=theia)]

Best

**Comment by sbrunato** [comment]
Hello Basile,
search results are paginated. If you want to retrieve more products, you can:
- ch

**Comment by sbrunato** [comment]
Hello Basile,
search results are paginated. If you want to retrieve more products, you can:
- change `items_per_page` in `search() ` parameters;
- iterate over `page` to get the next results;
See https://eodag.readthedocs.io/en/latest/api.html#eodag.api.core.EODataAccessGateway.search for more details.

**Comment by BasileGoussard** [comment]
Thank you very much @sbrunato !
