### ISSUE TITLE
Please better document how to use eodag as a local catalogue

### ISSUE THREAD

**Issue by rohel01** [CS-SI/eodag#152]
This is an important use-case to support local development and/or manage "private" data (ex: test data):

- Configuration eodag for local use
- Ingestion of local data in the catalog
- Import/export of this catalog to easily setup cloned environment
- Deletion of data

If possible, both CLI and Python API should be documented when relevant

**Comment by sbrunato** [comment]
Hello,
for the moment STAC static calog implementation is still in limited:
- https://eodag.readthedocs.io/en/latest/api.html#eodag.api.core.EODataAccessGateway.load_stac_items
- https://eodag.readthedocs.io/en/latest/tutorials/tuto_stac_client.html#STAC-Static-catalog

In `v2.1` we plan to implement a Search plugin for STAC static catalogs. Using it will permit to interact with the catalog's data like with another provider, like `sobloo` or `peps` (`eodag.search()` usage), and also create a STAC API server from these catalogs

**Comment by sbrunato** [comment]
Please see [tutorial: STAC client / static catalog](https://eodag.readthedocs.io/en/latest/tutorials/tuto_stac_client.html#STAC-Static-catalog) which shows how to configure EODAG with a STAC static catalog (local or remote)
