### ISSUE TITLE
Download only a subset of a given product not working

### ISSUE THREAD

**Issue by littlegeekA** [CS-SI/eodag#153]
When following the tutorial on computing NDVI with eodag: [tut](https://eodag.readthedocs.io/en/latest/tutorials/tuto_bandmath.html), it says, that:
"eodag-cube: This is a package that adds more capabilities to eodag, it allows to download only a subset of a given product (a sub extent for instance)"

However, when the subextent is used as in the provided code snippet 5, a message is provided:
Eodag does not support getting data from distant sources by now. Falling back to first downloading the product and then getting the data...

The same message is shown in the result of code snippet 5 in the tut. 

I understood from the description of the tut, that it should be possible to download only a sub-extent of the given product.

Has this not been implemented yet, is it not available for certain data, or is there some way to use this functionality?

**Comment by sbrunato** [comment]
Thank you for pointing at this issue in the tutorial description. 
In fact, 
> "eodag-cube: This is a package that adds more capabilities to eodag, it allows to download only a subset of a given product (a sub extent for instance)"

should be replaced with :
> "eodag-cube": This package, still in early stage, adds pixel access capabilities to eodag, enabling getting data in a xarray

We will include the fix in the next release.

Downloading a sub-extent of the product is not yet possible, but we plan to add individual bands and COG sub-extent data access using eodag-cube
