### ISSUE TITLE
configure Sentinel SAFE build for AWS STAC API providers

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#171]
After downloading a Sentinel product from STAC API providers (`astraea_eod`, `earth_search`) on AWS, build SAFE product the same way it is done for `aws_eos` (`S1_SAR_GRD`, `S2_MSI_L1C` and `S2_MSI_L2A`).

**Comment by Fahdben** [comment]
Hello Sylvain! 
Concerning `astraea_eod` when I search and download sentinel-1 data, i've noticed that the `manifest.safe` file is missing (although it exists on the s3 bucket). It's also missing from the EOProduct's assets. This could be a problem when reconstructing a SAFE folder.

**Comment by sbrunato** [comment]
hello @Fahdben and thanks! I have added the `manifest.safe` to the product's assets
