### ISSUE TITLE
[Plugins] Fields specified in conf_template.yml are disappearing

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#184]
**Describe the bug**
Fields specified in  `conf_template.yml` (ie. authentification and extract) are disappearing when ` PluginManager` is created, when the function ` load_config` (ligne 91) is called.

Before: 
![2021-03-18_17h19_30](https://user-images.githubusercontent.com/67311115/111660342-44325100-880e-11eb-8885-4e7e00662042.png)

After:
![2021-03-18_17h19_59](https://user-images.githubusercontent.com/67311115/111660394-53190380-880e-11eb-9f6f-9d8ad00cea2a.png)

**Code To Reproduce**
Just initialize `dag = EODataAccessGateway()` with a plugin enabled (ie. scihub) in a `conf_template.yml`

**Environment:**
 - Python version: `3.7`
 - EODAG version: `2.1.1`

**Comment by sbrunato** [comment]
Hello @remi-braun , thanks for this submit. We'll have a look at it quickly and post a fix as soon as possible
