### ISSUE TITLE
Distribute eodag on conda-forge

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#208]
Since all the current dependencies of eodag appear to be available on conda-forge, it appears possible to make it installable with conda by distributing it on *conda-forge*.

**Comment by sbrunato** [comment]
- [ ] @geonux for this we would need to create a geostorm account on http://anaconda.org/

**Comment by maximlt** [comment]
eodag is now available on conda-forge:
https://anaconda.org/conda-forge/eodag
