### ISSUE TITLE
Manage overly complicated geometries

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#210]
Sometimes, you have to search with overly complicated geometries coming from public datasets as OSM.
I have in mind the Grand Est region for example.

The big problem here is that some providers cannot ingest long WKTs and therefore the search has to be done on the convex_hull of the geometry to be ensure the query.

This leads to a side effect for non convex geometries: some queried tiles can be inside the convex hull but ouside the wanted geometry.
![2021-03-26_11h38_19](https://user-images.githubusercontent.com/67311115/112619827-0e9df100-8e28-11eb-95d5-7f454a2c73bd.png)

For now my workaround is to crunch the search result like this:

```python
crunched_query = current_query.crunch(FilterOverlap(config={"minimum_overlap": 0.001}),
                                                  geometry=actual_aoi)
```

I don't know if a layer can be added in the search function to manage this usecase ?

**Comment by maximlt** [comment]
Thanks @remi-braun for that interesting issue (and the nice image!).

There's actually internally already an attempt to simplify the sent WKT if it is too long:
```python
        @staticmethod
        def convert_to_rounded_wkt(value):
            wkt_value = wkt.dumps(value, rounding_precision=COORDS_ROUNDING_PRECISION)
            # If needed, simplify WKT to prevent too long request failure
            tolerance = 0.1
            while len(wkt_value) > WKT_MAX_LEN and tolerance <= 1:
                logger.debug(
                    "Geometry WKT is too long (%s), trying to simplify it with tolerance %s",
                    len(wkt_value),
                    tolerance,
                )
                wkt_value = wkt.dumps(
                    value.simplify(tolerance),
                    rounding_precision=COORDS_ROUNDING_PRECISION,
                )
                tolerance += 0.1
            if len(wkt_value) > WKT_MAX_LEN and tolerance > 1:
                logger.warning("Failed to reduce WKT length lower than %s", WKT_MAX_LEN)
            return wkt_value
```
With `WKT_MAX_LEN`= 1600`.

It's applied to: theia, peps, sobloo, creodias, mundi and onda.

Did you observe this issue with one of these providers?

**Comment by remi-braun** [comment]
I faced it on SciHub 😅 
The trick convex_hull + refinement is the most robust and easily implemented workaround I found.

I don't think this is really urgent, but I preferred highlighting this just in case

**Comment by maximlt** [comment]
Ok I see! I guess that you access SciHub with the `eodag-sentinelsat` plugin. Its configuration could be updated to round the wkt if need be, similar to theia for instance:
https://github.com/CS-SI/eodag/blob/cfc291ff30ab84fcf4f11798dc012437b6154d1c/eodag/resources/providers.yml#L589

I'd bet that it would fix the issue with the *Grand Est* region.

An edge case with *convex_hull + filter* could be that we allow multipolygon geometry. For instance, `locations=dict(country="FRA")` selects continental France, Corsica, French Guyana... I have to check that a convex hull of this kind of shape doesn't result in a selected area too wide compared to the original area of interest. A more robust approach here would be to convert a multipolygon to polygons and then apply *convex_hull + filter* for as many requests as polygons.

Another one might be that if *convex hull + filter* is implemented for `dag.seach`, the results obtained (single page) could be empty if the search is made on a wide temporal frame. That would be unlucky, but the first results (20 by default) could actually be located within an area between the convex hull envelope and the original geometry envelope, so completely filtered out by the cruncher.

Despite these points, I think this is an important case and that we have to cover it somewhere in the docs. Let's also see what @sbrunato has to say about it :)

And yes don't hesitate to report here any issue that you experience with eodag, it helps us maintaining it and can inform anyone else who experiences the same issue.

**Comment by sbrunato** [comment]
`eodag-sentinelsat` v0.3.0 is ready to publish, but I will include this quick-fix to the provider configuration! Thanks for pointing at this out!
