### ISSUE TITLE
Fallback mechanism to search for products with other providers

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#213]
The original issue https://github.com/CS-SI/eodag/issues/136 triggered a lot of interesting discussions, whose outcome is this issue and #214.

The feature request is to add a fallback mechanism so that if a search fails with the preferred provider then EODAG automatically tries to make the search on another set of providers, one after the other. It would cover the case of the preferred provider being down.

In order to implement this, we'd need to enforce the search plugins to raise a specific error (`RequestError` for instance), catch it in the main search methods and make the search again with the first fallback provider.

**Comment by maximlt** [comment]
@remi-braun feel free to correct me if I haven't reported your request properly ;)

**Comment by remi-braun** [comment]
This is exactly what I meant 👍 

The usecase for this feature is a fully automated chain:   
- I need to download a specific products *now*
- I have a list of registered provider that are sorted according to some criteria (ie free and stable first, costly last)
- I don't care from where the product comes from, I just need the data
