### ISSUE TITLE
Avoid trying to order an OFFLINE product

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#215]
From @remi-braun in https://github.com/CS-SI/eodag/issues/214

> Maybe add the LTA order as a parameter, as it is not needed in every usecase (sometimes, sb just want to download everything he can without triggering any LTA retrieval)

LTA: Long Term Archive

The `HTTPDownload` plugin (used by creodias, onda, theia, peps, sobloo) can automatically try to order a product if its status is *OFFLINE*, and can download it afterwards.

The feature request is to add a way to avoid trying to order an *OFFLINE* product.

This could be done in at least two complementary ways:
1. Document the way to filter out *OFFLINE* products from the result of a search. This can be done as follows currently:
```python
from eodag.plugins.crunch.filter_property import FilterProperty
dag.set_preferred_provider("peps")
prods, _ = dag.search(...)
online_prods = prods.crunch(FilterProperty({"storageStatus": "ONLINE", "operator": "eq"}))
dag.download_all(online_prods)
```
2. Add a parameter to pass as a kwarg to `EODataAccessGateway.download_all` (not sure it's relevant for `download`), e.g. `skip_offline`, that would be passed to the HTTPPlugin and, if `True`, would stop trying to download this product, which would lead to `download_all` trying to download the next product.

**Comment by maximlt** [comment]
@remi-braun Would 1. be enough for your use case here?

I note though that some of the work required by 2., at least the internal plugin one, would be required to implement #214 to skip ordering a product.

**Comment by remi-braun** [comment]
Thanks for creating a new feature request for this !

My usecase would be the second point, as:
- I always query and download all on one occasion, using the products on the spot
- I am never using the retrieved LTA products when finally available

(Currently, I stopped ordering LTA for nothing, I just don't try to download products that are offline for all my registered providers)
