### ISSUE TITLE
Sentinel SAFE / non-SAFE product types distinction

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#216]
All providers do not provide Sentinel products in SAFE format, which means for example that searching `S2_MSI_L1C` products on `peps` or `astraea_eod` can return products packaged differently, and differently formatted ids.

We should add more product types to be able to distinguish:
- Sentinel products in SAFE / jp2 format (S2_MSI_L1C peps)
- Sentinel products in non-SAFE / jp2 format (S2_MSI_L1C astraea_eod)
- Sentinel products in cog format (sentinel-s2-l2a-cogs earth_search)

See https://github.com/CS-SI/eodag/issues/136#issuecomment-808082569, #171

**Comment by Fahdben** [comment]
Yes! this would be very useful to avoid the data format confusion

**Comment by sbrunato** [comment]
A suggestion:
- Sentinel products in SAFE / jp2 format (S2_MSI_L1C peps) : `S2_MSI_L1C` (as standard)
- Sentinel products in non-SAFE / jp2 format (S2_MSI_L1C astraea_eod) : `S2_MSI_L1C_JP2` (rare, or for unconfigured provider)
- Sentinel products in cog format (sentinel-s2-l2a-cogs earth_search) : `S2_MSI_L1C_COG`

Please comment if someone has other ideas for these names, or if these ones seem good

**Comment by maximlt** [comment]
Just a couple of naive questions :innocent: :
* I see that we build SAFE products when they're downloaded from AWS. Why doesn't this work with *astraea_eod*?
* Will these new product types have the same definition in *product_types.yml*?

Otherwise I think the names you suggest are fine :+1:

**Comment by sbrunato** [comment]
>     I see that we build SAFE products when they're downloaded from AWS. Why doesn't this work with _astraea_eod_?
The configuration needs to be done for each aws provider. It is now done for `astraea_eod` and `earth_search`, see #218 

>     Will these new product types have the same definition in _product_types.yml_?
Yes, all product types have to be described in this file
