### ISSUE TITLE
Wrong ID for earch_search with S2_MSI_L1C/S2_MS1_L1A

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#217]
As noted in https://github.com/CS-SI/eodag/issues/136#issuecomment-808082569, the ID attributed to an S2_MSI_L1C product obtained from earth_search is inconsistent with other providers:
```json
{
   "astraea_eod":"S2A_OPER_MSI_L1C_TL_EPAE_20200815T043159_A026884_T56XMG_N02.09",
   "aws_eos":"S2B_MSIL1C_20200816T023549_N0209_R089_T56XMG_20200816T041557",
   "creodias":"S2A_MSIL1C_20200815T021611_N0209_R003_T56XMH_20200815T043159",
   "earth_search":"S2A_56XMG_20200815_0_L1C",
   "mundi":"S2A_MSIL1C_20200815T021611_N0209_R003_T56XMH_20200815T043159",
   "peps":"S2A_MSIL1C_20200815T021611_N0209_R003_T56XMG_20200815T043159",
   "sobloo":"S2A_MSIL1C_20200815T021611_N0209_R003_T56XMH_20200815T043159"
}
```

earth_search actually provides the right ID, it"s stored in the attribute *features.properties.sentinel:product_id:*, see for instance this [response](https://earth-search.aws.element84.com/v0/search?datetime=2020-08-08T00:00:00.000Z/2020-08-16T00:00:00.000Z&bbox=[151.0,73.0,152.0,74.0]&collections=[%22sentinel-s2-l1c%22]&limit=1&page=1).

![image](https://user-images.githubusercontent.com/35924738/113116203-86479380-920d-11eb-8be7-bbe9da3a3733.png)

This is also true for S2_MSI_L1A products (see [this response](https://earth-search.aws.element84.com/v0/search?datetime=2020-08-08T00:00:00.000Z/2020-08-16T00:00:00.000Z&bbox=[151.0,73.0,152.0,74.0]&collections=[%22sentinel-s2-l2a%22]&limit=1&page=1))

**Comment by sbrunato** [comment]
As mentioned here https://github.com/CS-SI/eodag/pull/218#issuecomment-812596493, `earth_search` and `astraea_eod` have their own `id` format to keep the ability to search by `id` on these providers.
The `title` attribute format  has been updated on these providers with #218, to make the destination path consistent with others providers.
