### ISSUE TITLE
Error while downloading a quicklook in a directory where the product has already been downloaded and extracted

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#226]
It might be an edge case but I got caught by this one.

```
Traceback (most recent call last):
  File "/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/snippet_quicklook_peps.py", line 20, in <module>
    prods[0].get_quicklook(base_dir="/tmp")
  File "/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/eodag/api/product/_product.py", line 392, in get_quicklook
    with open(quicklook_file, "wb") as fhandle:
IsADirectoryError: [Errno 21] Is a directory: '/tmp/S2B_MSIL1C_20200815T030549_N0209_R075_T55XEB_20200815T051416'
```

I first downloaded a product in a directory, say `work`. The product was automatically extracted to `work/productID`. I then tried to download the quicklook of that product with `get_quicklook` in the same directory `work`. If not provided, a quicklook get its filename from the product's ID:
https://github.com/CS-SI/eodag/blob/fec965f791a74dbf658e0833e1507b7ac950d09d/eodag/api/product/_product.py#L344-L347

In that case then, `get_quicklook` tried to save the quicklook to `work/productID` which was an existing folder, hence the error reported above.

I assume quicklooks get their filename from the product's ID because some providers don't provide an URL, instead they provide the encoded image content (*onda*, at least).

Here I guess the simplest thing to do would be to check if the file path of the quicklook to download is a directory, and raise a nicer error in that case.

**Comment by sbrunato** [comment]
I am not sure if we need to handle such a case.

By default, the quicklook is downloaded to the directory `os.path.join(outputs_prefix, "quicklooks")`. If a user changes it to `outputs_prefix` and do not specify a destination filename it will conflict with the product itself as expected.

Anyway, we may update the docstring to make more clear that the default destination will be `{outputs_prefix}/quicklooks/{product.id}`
