### ISSUE TITLE
Kwargs passed to guess a product type are propagated

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#229]
A search made with the following criteria guesses that it should use the product type `S2_MSI_L1C`:

```python
from eodag import EODataAccessGateway
dag = EODataAccessGateway()
dag.set_preferred_provider("peps")
search_criteria = {
 'start': '2021-03-01',
 'end': '2021-03-31',
 'geom': {'lonmin': 1, 'latmin': 43, 'lonmax': 2, 'latmax': 44},
 'instrument': 'MSI',
 'platform': 'SENTINEL2',
 'platformSerialIdentifier': 'S2A',
 'processingLevel': 'L1',
 'sensorType': 'OPTICAL'
}
dag.search(**search_criteria)
```

The URL sent is this one:

https://peps.cnes.fr/resto/api/collections/S2ST/search.json?instrument=MSI&platform=S2A&processingLevel=L1&sensorType=OPTICAL&startDate=2021-03-01&completionDate=2021-03-31&geometry=POLYGON ((1.0000 43.0000, 1.0000 44.0000, 2.0000 44.0000, 2.0000 43.0000, 1.0000 43.0000))&productType=S2MSI1C&maxRecords=20&page=1

As it can be seen the URL has the "hint" kwargs (e.g. `instrument`) as query parameters. I don't know whether they should be preserved or not. The problem here actually is that the search returns 0 results while it should return some in this area and time period. By removing `processingLevel=L1` the request returns some results, but not the same number as if the search was made before hints and just with `productType="S2_MSI_L1C"`.

**Comment by sbrunato** [comment]
One thing that can be done to keep the actual features (both _guess-product-type_ and _custom-query-parameters_) is to:
- keep all query parameters if `productType` is specified
- remove from query parameters the ones that where used to guess the product type if it wasn't specified

**Comment by maximlt** [comment]
Sounds good to me!
