### ISSUE TITLE
download_all removes the products contained by the passed SearchResult

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#230]
The items of a `SearchResult` (it could also just be a list of `EOProduct`) passed to `download_all` can get cleared by the method. I observed this behaviour with downloading products from *peps*. If it is the intended behaviour, it should be well documented because it is quite surprising.

If not, the problem comes certainly from this line (*PEPS* uses a HTTPPlugin which itself uses the base implementation of `search_all`):
https://github.com/CS-SI/eodag/blob/fec965f791a74dbf658e0833e1507b7ac950d09d/eodag/plugins/download/base.py#L308

Run this snippet to reproduce the bug:

```python
from eodag import EODataAccessGateway
from eodag.api.search_result import SearchResult

dag = EODataAccessGateway('path/to/peps_config.yml')  # Adapt the path
dag.set_preferred_provider("peps")

search_criteria = dict(
    productType='S2_MSI_L1C',
    start='2021-03-01',
    end='2021-03-31',
    geom={"lonmin": 1, "latmin": 42, "lonmax": 5, "latmax": 46},
)
search_results = dag.search_all(**search_criteria)
print(f'Got {len(search_results)} products.')

# Download the smallest files
sorted_prods_per_size = SearchResult(
    sorted(search_results, key=lambda p: p.properties["resourceSize"])
)
prods_to_download = sorted_prods_per_size[:2]

# Just to make sure not to order products
assert all([p.properties["storageStatus"] == "ONLINE" for p in prods_to_download])

paths = dag.download_all(prods_to_download)

if not prods_to_download:
    print("Oh oh I'm empty now")
```

If this is a bug, we should check the behaviour of the other download plugins.

**Comment by maximlt** [comment]
For the record, I discovered this behaviour while I was trying to inspect the value of the attribute `location` of the downloaded products. I have the feeling but need to have a closer look at it that it is not being updated to reflect the local path after the download has succeeded.

**Comment by sbrunato** [comment]
This is not the expected behavior. We may do a copy of the products list to preserve it duing `download_all()` but also update products location when each individual download is done

**Comment by maximlt** [comment]
This was nicely spotted by the ORFEO toolbox:
https://gitlab.orfeo-toolbox.org/s1-tiling/s1tiling/-/blob/develop/s1tiling/libs/S1FileManager.py#L380
