### ISSUE TITLE
Inconsistent filepaths returned by the download methods

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#232]
`download_all` returns for instance:
```python
['/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/docs/notebooks/api_user_guide/eodag_workspace_download/S2A_MSIL1C_20201229T110451_N0209_R094_T31TCL_20201229T131620/S2A_MSIL1C_20201229T110451_N0209_R094_T31TCL_20201229T131620.SAFE',
 '/home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/docs/notebooks/api_user_guide/eodag_workspace_download/S2A_MSIL1C_20201226T105451_N0209_R051_T31TCK_20201226T130209/S2A_MSIL1C_20201226T105451_N0209_R051_T31TCK_20201226T130209.SAFE']
```

while `download` returns:
```
'file:///home/maxime/TRAVAIL/06_EODAG/01_eodag/eodag/docs/notebooks/api_user_guide/eodag_workspace_download/S2A_MSIL1C_20201116T105331_N0209_R051_T31TCL_20201116T130215/S2A_MSIL1C_20201116T105331_N0209_R051_T31TCL_20201116T130215.SAFE'
```

I think all the download methods should return a consistent local path. It'd say they should all prepend `file://` since it's documented in `download`. It seems it's been there for a while.

**Comment by maximlt** [comment]
Ok it's a little more complex than the issue described.

The logic to prepend a path with `file://` is now in `EOProduct.download`, which itself calls `plugin.download`.  `EOProduct.download` is called by `EODataAccessGateway.download` but not by `EODataAccessGateway.download_all`, which directly calls `plugin.download_all`.

It is not clear which method should take the responsibility to format the output path:
1. Should it be each plugin method, i.e. `download` and `download_all`?
2. Should it only be `EOProduct.download`? In that case, each plugin method should call it.

I checked the code of eodag-sentinelsat. It uses the `download_all` method provided by the package `sentinelsat` so 2. could not be implemented there.

I'd then be in favor of 1. In that case we'd have to update the docstring of the plugin's base methods: `download.download`, `download.download_all`, `api.download`, `api.download_all` (this one actually doesn't exist).

There are other discrepancies:

* eodag-sentinelsat: both `download` and `download_all` methods do not return paths following the File URI scheme
* Windows: Paths returned by `EODataAccessGateway.download` do not follow the File URI scheme. For example, `file://c:\user\download`, which is quite far from what it should be `file:///c:/user/download` (see the [wikipedia reference](https://en.wikipedia.org/wiki/File_URI_scheme#Windows))

So, given all that, I actually wonder why in the first place it was decided that paths returned by `EOProduct.download` should follow the file URI scheme? Do you happen to know why @sbrunato ? Should we consider returning a "normal" file path instead?

Whatever we decide, I feel that we will need to bump the version to 2.3.0, this would be quite a change.

NB:
We probably need at least one end to end test that completely download a product.

**Comment by sbrunato** [comment]
Ok, here is a a summary of how we have decided to handle these paths:

- we keep `file://` URI scheme in `product.location`
- `download()` and `download_all()` methods must provide paths without `file://`
- we will fix `product.location` for windows, providing `file:///c:/user/download` instead of `file://c:\user\download`

**Comment by maximlt** [comment]
> eodag-sentinelsat: both download and download_all methods do not return paths following the File URI scheme

I was wrong, `scihub.download` returned a path following the File URI scheme. Not `scihub.download_all` though.
