### ISSUE TITLE
Error loading user config files with settings of providers loaded via plugins

### ISSUE THREAD

**Issue by ahuarte47** [CS-SI/eodag#234]
**Install sentinelsat plugin**
```
python -m pip install eodag
python -m pip install eodag-sentinelsat
```

Append your own "scihub" provider settings to an user configuration file...

![image](https://user-images.githubusercontent.com/5576272/114627081-f564c380-9cb4-11eb-990b-2aa901040207.png)

**Code To Reproduce**
CLI command:
```sh
eodag --verbose search --conf "eodag-user_conf.yml" ....
```
**Output**
![image](https://user-images.githubusercontent.com/5576272/114627430-86d43580-9cb5-11eb-80af-5c9b5a398734.png)

**Environment:**
 - Python version: 3.7.4
 - EODAG version: 2.2.0

**Comment by sbrunato** [comment]
Hello, many thanks for this PR!
