### ISSUE TITLE
Inconsistent progress bar between download and download_all

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#237]
**In a notebook**, I've observed that `EODataAccessGateway.download_all` was automatically selecting the right progress bar while `EODataAccessGateway.download` wasn't.

It'd be nice if `EODataAccessGateway.download` could also select automatically the right progress bar. We could then completely remove all the `from eodag.utils import NotebookProgressCallback; dag.download(product, progress_callback=NotebookProgressCallback())` from the notebooks :+1:

**Comment by sbrunato** [comment]
>  It'd be really nice to be able to pass progress_callback=False to suppress any progress bar display. I'm sure it'd be useful.

We may see if we implement it later as this is not a priority, nor a bug.

> If progress_callback=None (by default), then eodag should guess which progress bar to use with get_progress_callback(). This seems to be the current logic, let's stick to that.

This has to be the default behavior.

> If progress_callback=NotebookProgressCallback() or progress_callback=ProgressCallback() is passed, then the type of the callback passed should be reused.

With `tqdm.auto`, we will not use to handle this any more. See https://github.com/CS-SI/eodag/issues/239#issuecomment-823857707

>  To simplify the docstring to a higher level description that reflects what we decide to implement

We may only explain that `progress_callback` must be an instance of `eodag.utils.ProgressCallback`

**Comment by floriandeboissieu** [comment]
>     * If `progress_callback=None` (by default), then eodag should guess which progress bar to use with `get_progress_callback()`. This seems to be the current logic, let's stick to that.

My 2cents on this parameter:
- If `progress_callback=None`, no progress bar
- If `progress_callback="auto"`, guess progress bar

**Comment by sbrunato** [comment]
for this parameter, mixing all suggestions, we can use something like:
```py
def download(self, progress_callback=ProgressCallback(), **other_params):
    if not progress_callback:
        progress_callback = ProgressCallback(disable=True)
    # [...]

class ProgressCallback(object):
    def __init__(self, max_size=None, disable=False):
        self.disable = disable
        # [...]

    def __call__(self, **params):
        # [...]
        if self.pb is None:
            self.pb = tqdm(
                disable=self.disable,
                **tqdm_params
            )
        # [...]
```
Not providing `progress_callback` will led to the creation of a default progress bar, but giving it `False`, `None` ot other False-evaluated value will create a disabled tqdm bar.

**Comment by maximlt** [comment]
@sbrunato one thing I'm not sure about this implementation is that the default argument of `progress_callback` is progress bar is instance. The download plugins may need more than one (`download` to display the download itself and the extraction).

I would reuse the API suggested by @floriandeboissieu:
* `progress_callback=None`: no progress bar
* `progress_callback="auto"`: automatic progress bar

With `"auto"` being the default for all the `core.download`, `core.download_all` and `product.download`, e.g.:
```python
def download(self, progress_callback="auto", **kwargs)  # core.download
```
(I really like that currently the progress bar is displayed by default, wherever I run the code)

Since we want to introduce this change smoothly, we would need to:
* deprecate the `ProgressCallback` and `NotebookProgressCallback`
* still accept for a while `dag.download(product, progress_callback=ProgressCallback()` and `dag.download(product, progress_callback=NoteProgressCallback()`

I think we could add a new class for the progress callbacks for this transition, which would have the implementation you suggested, but with a different name:
```python
class AutoProgressCallback(object):
    def __init__(self, max_size=None, disable=False):
        self.disable = disable
        # [...]

    def __call__(self, **params):
        # [...]
        if self.pb is None:
            self.pb = tqdm(
                disable=self.disable,
                **tqdm_params
            )
        # [...]
```

With that in place, we could update `get_progress_callback` (or create a new function) in `eodag.utils.__init__.py` to accept `progress_callback` and return the right progress bar:
```python
def get_progress_callback(user_progress_callback=None):
    if not user_progress_callback:
        return AutoProgressCallback(disable=True)
    elif user_progress_callback == "auto":
        return AutoProgressCallback()
    elif isinstance(user_progress_callback, (ProgressCallback, NotebookProgressCallback)):
        with warnings.catch_warnings():
            warnings.simplefilter("always", DeprecationWarning)
            warnings.warn(
                    f"Call to deprecated progress callback {type(user_progress_callback)}, use either 'auto' or None",
                    category=DeprecationWarning,
                    stacklevel=2,
                )
        return AutoProgressCallback()
    else:
        raise ValueError("'progress_callback' accepts only 'auto' or None")
```

The contract with the download plugins would be that they must use this function to create a progress bar, by using the value of `progress_callback` passed by either core or product.
```python
def download(self, product, progress_callback=None, **kwargs):  # plugin.download
    progress_bar = get_progress_callback(progress_callback)
    # Do something with the progress bar
    # [...]
```

What do you think about that?
