### ISSUE TITLE
Default behaviour for extracting products

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#238]
I've just used `eodag-sentinelsat` and was surprised to see I had to set the `extract` parameter to a value (True or False). Before that, I never set this value and it seems to me that products were always extracted.

Currently in providers.yml:
* usgs: true
* aws_eos: (irrelevant as AWS download)
* theia: true
* peps: true
* sobloo: true
* creodias: true
* mundi: true
* (wekeo): broken now
* onda: true
* astraea_eod: (irrelevant as AWS download)
* usgs_satapi_aws: (irrelevant as AWS download)
* earth_search: (irrelevant as AWS download)
* earth_search_cog: (irrelevant as COG)

The logic in `plugins.download.base.Download._finalize` is to set it to False if `extract` is not provided (either dynamically through kwargs or via configuration):
https://github.com/CS-SI/eodag/blob/0632e4147f26119bea43e0672f6d06e75d216a20/eodag/plugins/download/base.py#L151-L161

It is called by `HttpDownload.download` and `UsgsApi.download` (and by `Download._prepare_download` to finalize extracting a product if it couldn't be achieved previously for some reason).

The template indicates:
```
            extract:  # whether to extract the downloaded products (true or false).
```

Should we:

* Specify that the default behavior is to automatically extract products?
* Update `_finalize` accordingly?
* Indicate to plugin developers that they should extract automatically by default?
* Update eodag-sentinelsat accordingly?

**Comment by sbrunato** [comment]
> - Specify that the default behavior is to automatically extract products?
> - Update `_finalize` accordingly?

Yes, as it is the chosen behavior in `providers.yml` we should also use it in `_finalize()`

> * Indicate to plugin developers that they should extract automatically by default?

yes

> * Update eodag-sentinelsat accordingly?

Yes, the plugin must be updated to extract by default even if `extract` is not specified in user configuration
