### ISSUE TITLE
Quiet download

### ISSUE THREAD

**Issue by floriandeboissieu** [CS-SI/eodag#250]
**Is your feature request related to a problem? Please describe.**
It does not seem possible to remove progress bar, thus no quiet download possible.

**Describe the solution you'd like**
It would be nice to have the possibility to shut down progress_callback in case a quiet download is wanted, however keeping the possibility to have a message only telling the download of which file has started

**Describe alternatives you've considered**
- Keep the progress_callback to the value given in args (None if it is the case without setting systematically a default value),
- Operate progress_callback only if not None

**Comment by maximlt** [comment]
Timely feature request, we just talked about it in #237 

The current behavior for displaying progress bars isn't consistent among the various download methods and their actions (download, extract). The most widespread behavior though is that the right progress callback/bar is detected by EODAG (classic vs. notebook/ipython) and used automatically.

The suggestions are:
* `progress_callback=None` => Progress bar automatically chosen and displayed by eodag
* `progress_callback=False` => No progress bar / Your quiet download
* Or `progress_callback` must be passed an object that must be an instance of `eodag.utils.ProgressCallback`

**Comment by floriandeboissieu** [comment]
Ok, thanks, thus I'll follow the issue and close this one.

**Comment by sbrunato** [comment]
@floriandeboissieu this has been fixed by PR GH-276 (available in `develop` branch)

**Comment by floriandeboissieu** [comment]
Thanks for noticing me!
