### ISSUE TITLE
Extract SAFE products without intermediate directory

### ISSUE THREAD

**Issue by floriandeboissieu** [CS-SI/eodag#251]
**Describe the bug**
Extraction is adding a useless subdirectory, example:
extracting my_data/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922.zip leads to 
my_data/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922.SAFE

In order to be coherent with unzipping outside eodag, e.g. `unzip S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922.zip`, in my opinion it would be preferable to lead to my_data/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922.SAFE.

**Comment by maximlt** [comment]
@sbrunato is there a particular reason why the product is extracted in a subdirectory instead at the root of `outputs_prefix`?

**Comment by sbrunato** [comment]
Before downloading a product, we check it has not already been downloaded with :
- its `record_filename` (in `.downloaded/`) 
- and its destination file or folder (`fs_dir_path` in the code code below)
https://github.com/CS-SI/eodag/blob/0632e4147f26119bea43e0672f6d06e75d216a20/eodag/plugins/download/base.py#L138-L139

In your example, `my_data/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922.SAFE`:
- `my_data` is the root of your destination folder, `outputs_prefix` parameter in eodag's configuration
- `my_data/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922` is `fs_dir_path` in the code above, with `fs_dir_path = f"{outputs_prefix}/{product.properties[title]}"`
- `S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922.SAFE` is the subfolder name used for the SAFE-formatted product

**Comment by floriandeboissieu** [comment]
@sbrunato what you are saying is that it is not possible to get/build the root directory of the zip file from the search result properties? 

For PEPS, product.properties["title"]+'.SAFE' would do, and could be integrated as pattern string in the configuration file, e.g. "{title}.SAFE". But I don't know if it could be generalized to other data providers.

> Before downloading a product, we check it has not already been downloaded with :
> 
>     * its `record_filename` (in `.downloaded/`)
> 
>     * and its destination file or folder (`fs_dir_path` in the code code below)
>       https://github.com/CS-SI/eodag/blob/0632e4147f26119bea43e0672f6d06e75d216a20/eodag/plugins/download/base.py#L138-L139

This code block raises another issue for me, files that would have been downloaded without eodag (or moved without the .downloaded directory, which is a secret directory) would not be recognized by eodag as already there and downloaded again, am I right?

Any specific reason I don't see for checking on `record_filename` ? (and actually for the existence of such a file?)

**Comment by maximlt** [comment]
> `fs_dir_path = f"{outputs_prefix}/{product.properties[title]}"`

@sbrunato , is there any particular reason why an intermediate directory (`product.properties[title]`) has to be created?

**Comment by maximlt** [comment]
@floriandeboissieu , getting back to your original issue (useless subdirectory), has this actually caused a bug in your application/script/workflow?

**Comment by floriandeboissieu** [comment]
@maximlt , no it hasn't caused a "bug" really, sorry I should have opened a blank issue, you can remove the label. 

It is just making the database I already have downloaded with peps_download incompatible with eodag at the moment. Same problem occurs with R package sen2r (which is also used a lot in my neighborhood). 

I could reformat the database on my side to fit to eodag, and modify the scripts/applications in consequence, but it would create compatibility issues with peps_download and sen2r downloaded data. That is why I was digging what was possible on your side, the unzipping directly to output_prefix seeming the straightest way of doing it in my opinion  :-).

**Comment by sbrunato** [comment]
> @sbrunato , is there any particular reason why an intermediate directory (product.properties[title]) has to be created?

For homogeneity purpose

> @sbrunato what you are saying is that it is not possible to get/build the root directory of the zip file from the search result properties?

It is possible, but for now we use `f"{outputs_prefix}/{product.properties[title]}"` as destination by default for all providers / product types.

This can be updated, but before we'll have to check how it may impact other users and projects using eodag. 

@floriandeboissieu we'll keep you informed in this issue if we update this sub-directories behavior

**Comment by aoyono** [comment]
Just to add a bit of a history here. If I remember well, most of the other providers giving zip files at download have the product bundled at the top level of the zip file (without any sub-directory) unlike PEPS and sobloo. Thus the use of `f"{outputs_prefix}/{product.properties[title]}"`, where it's expected that the content of the product will be under that directory. In fact, the introduction of the `archive_depth` config option was due to PEPS. The intent was to attach the location of the directory where the user will actually see the content of the product (metadata et al.). So when you download a PEPS product, the `EOProduct(...).location` is `/path/to/my_data/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922/S2A_MSIL1C_20180619T132231_N0206_R038_T22KGV_20180619T150922.SAFE`. This also explains why `archive_depth` is set to 2 in the default providers configuration only for PEPS and sobloo (related issue: #266). The default value for it is 1 and it's assumed that this is the most general case, so no need for explicit configuration.

**Comment by sbrunato** [comment]
Thanks @LucHermitte , could you also please have a look to the poll on https://github.com/CS-SI/eodag/discussions/446 and vote for the output folder pattern that would match your needs best ?
