### ISSUE TITLE
Remove zip after extraction

### ISSUE THREAD

**Issue by floriandeboissieu** [CS-SI/eodag#252]
**Is your feature request related to a problem? Please describe.**
At the moment, zip is left in the downloading directory, although it has been extracted, but there is no clue of it in the download output (only  the uri of the extracted file). Thus, it would be nice if the zip could be automatically removed after extraction.

By the way, I think it would be wise to use a temporary directory (tempfile.TemporaryDirectory) while extracting to avoid partially extracted files if interrupted.

**Comment by maximlt** [comment]
Hi @floriandeboissieu, thanks for this feature request :)

We already had an issue open for that, see #144, so I'll close this one and copy there your comment about using a temp directory :+1:
