### ISSUE TITLE
`archive_depth` only set for PEPS and sobloo

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#266]
`plugins.download.base.Download._finalize` takes care of extracting a product if required and returns the path to the product. There is a mechanism to inspect 

There is a mechanism to handle which path to return when the product is extracted:
https://github.com/CS-SI/eodag/blob/bab1b7e9c81e096d62ef6b5a2a736445c3b546d7/eodag/plugins/download/base.py#L275-L284

PEPS and sobloo have `archive_depth: 2` in their config, which means that the path returned after extraction is `outputs_prefix/product_title/subdirectory`.

I guess it needs to be set for some other providers, e.g. onda, theia, creodias (those that make use of the `HTTPDownload` plugin).

(I saw that while updating `eodag-sentinelsat`.)

**Comment by maximlt** [comment]
As the comment says `# WARNING: A strong assumption is made here: there is only one subdirectory per level `, I'm not sure whether this mechanism is robust to all the products made available by these providers.

**Comment by aoyono** [comment]
See the [following comment](https://github.com/CS-SI/eodag/issues/251#issuecomment-877087528)

**Comment by sbrunato** [comment]
See also the poll on https://github.com/CS-SI/eodag/discussions/446 to vote for the output folder pattern that you prefer
