### ISSUE TITLE
Searching with the use of different imagery paremeters

### ISSUE THREAD

**Issue by aleksandraradecka1** [CS-SI/eodag#277]
Hello!

I would like to ask if the EODAG's search functionality is now fully operational. While searching for images acquired by different sensors (using Creodias credentials) I had a feeling that the parameters presented in your tutorials (basic and advanced) work well. However adding other parameters listed in 'params_mapping.csv' e.g. 'processingLevel', 'sensorMode' provided me with confusing results. These parameters were either not working at all or did not filter imagery correctly. I tested both parameter names listed in 'param' and 'creodias_mapping' columns, also entered them as normal parameters and as kwargs. I have also noticed that the name 'productType' is used both as EODAG's own parameter and one of Creodias', two having different definition.

I would be very greatful for explaining these issues.

Best regards, 
Aleksandra Radecka (aleksandra.radecka@pw.edu.pl)

**Comment by sbrunato** [comment]
Hello @aleksandraradecka1 , and thanks for reporting this issue.
The list of queryable parameters is something we should better document, and the file [params_mapping.csv](https://eodag.readthedocs.io/en/latest/_static/params_mapping.csv) is not very readable (see also https://github.com/CS-SI/eodag/issues/242#issuecomment-823912368).

- In [params_mapping.csv](https://eodag.readthedocs.io/en/latest/_static/params_mapping.csv) the column `creodias_mapping` lists the parameters that will appear in the found product metadata. And `creodias_query` lists the queryable parameters. Very few are configured, and are:
    - `cloudCover`
    - `completionTimeFromAscendingNode`
    - `geometry`
    - `id`
    - `productType`
    - `startTimeFromAscendingNode`
 - If a parameter appears in `creodias_mapping` but not in `creodias_query` (e.g. `orbitDirection`), EODAG will set it as a non-queryable parameter.
 - If a parameter does'nt appears in `creodias_mapping` neither `creodias_query` (e.g. `relativeOrbitNumber`), EODAG will be able to use it as a [custom/extra query parameter](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/4_search.html#Extra-query-parameters).
 - The parameters `"instrument", "platform", "platformSerialIdentifier", "processingLevel", "sensorType"` are used to [guess the product type](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/4_search.html#Guess-a-product-type) and will not be used in the query.

Creodias supports many more queryable parameters (see https://finder.creodias.eu/resto/api/collections/Sentinel2/describe.xml), and EODAG should be updated to enable this feature:

- [ ] Add more queryable parameters for Creodias in `providers.yml`

**Comment by aleksandraradecka1** [comment]
Dear Sylvian, 

thank you very much for the explanation! Everything is clear now and I agree that a more detailed documentation would be helpful.

**Comment by sbrunato** [comment]
@aleksandraradecka1 , until we update creodias queryable parameters list in eodag, you can now dynamically update the settings using:
```py
from eodag import EODataAccessGateway

dag = EODataAccessGateway()
dag.update_providers_config("""
creodias:
    search:
        metadata_mapping:
            orbitDirection:
                - orbitDirection
                - '$.properties.orbitDirection'
""")
```
Then you can search using this parameter that was previously configured as non-queryable:
```py
>>> dag.set_preferred_provider("creodias")
>>> extent = {'lonmin': 1.23, 'lonmax': 1.68, 'latmin': 43.42, 'latmax': 43.76}
>>> search_results, total_count = dag.search(productType="S2_MSI_L1C", geom=extent, start='2021-01-01', end='2021-05-31')
>>> total_count
59
>>> search_results, total_count = dag.search(orbitDirection="ascending", productType="S2_MSI_L1C", geom=extent, start='2021-01-01', end='2021-05-31')
>>> total_count
4
```

Please note that this has just been enabled/fixed by GH-288, and is only available in the `develop` branch for the moment.
