### ISSUE TITLE
Unable to disable the Progress Bar

### ISSUE THREAD

**Issue by maximlamare** [CS-SI/eodag#297]
I am using the Python API with Jupyter Notebook. I am trying to mute the download progress bar because each iteration prints a new line (despite having `jupyter-js-widgets/extension  enabled`).

**The problem I am trying to get rid of**:

![Screenshot from 2021-06-08 19-18-42](https://user-images.githubusercontent.com/32132761/121229530-5f04e680-c88e-11eb-8ba0-4ca4cd80ba00.png)

**What I have tried**

1. 
```py
dag.download(all_products[0], progress_callback=None)
```
prints the progress.

2.

```py
setup_logging(0, no_progress_bar=True)
```

yields: `TypeError: setup_logging() got an unexpected keyword argument 'no_progress_bar'`

3.

```py
setup_logging(verbose=0)
dag.download(all_products[0])
```
prints the progress.

4.

`eodag.utils.ProgressCallback` only has the following arguments (less than the [documentation](https://eodag.readthedocs.io/en/latest/api_reference/utils.html#eodag.utils.ProgressCallback), i.e. no `disable`?)

- 'desc',
-  'max_size',
- 'pb',
-  'position',
-  'reset',
-  'unit',
-  'unit_scale'

5.

Also tried:

```py
from tqdm.notebook import tqdm

pg = ProgressCallback(tqdm(disable=True))

dag.download(all_products[0], progress_callback=pg)
```

prints the progress.

**Environment:**
- In Anaconda: `conda 4.10.1`
 - Python version: `Python 3.9.4`
 - EODAG version: `eodag (Earth Observation Data Access Gateway): version 2.2.0`
- Jupyter:

```
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_console           6.4.0              pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py39hf3d152e_0    conda-forge
```
**Additional context**

Also tried in JupyterLab with no success

I would appreciate some pointers to either fix the progress bar or remove it. Thanks for reading through this!

**Comment by sbrunato** [comment]
Hello @maximlamare , and many thanks for the feedback.

The problem is that *disabling the progress bar* is a feature that is only in the `develop` branch for the moment (documentation https://eodag.readthedocs.io/en/latest). The stable version available on pypi or conda-forge refers to the `master` branch (documentation https://eodag.readthedocs.io/en/stable or https://eodag.readthedocs.io).

So, if you want to have this feature before eodag v2.3.0 is released (it should be soon), you can install it from the develop branch:
```bash
git clone https://github.com/CS-SI/eodag.git
cd eodag
git checkout develop
python -m pip install .

# or directly
python -m pip install git+https://github.com/CS-SI/eodag.git@develop
```

- [ ] However, we should clarify the usage of `develop` / `master` branches, the link to the appropriate documentation, and the published versions. This could be done by publishing beta versions more often, and having the version number in the documentation more visible

**Comment by sbrunato** [comment]
Using the `develop` branch, you should now have:
> 1. 
```py
dag.download(all_products[0], progress_callback=None)
```
Same as `dag.download(all_products[0])`, eodag creates a default progress bar

> 2.

```py
setup_logging(0, no_progress_bar=True)
```

No progress bar should be displayed

> 3.

```py
setup_logging(verbose=0)
dag.download(all_products[0])
```
No progress bar should be displayed

> 4.
> `eodag.utils.ProgressCallback` only has the following arguments (less than the [documentation](https://eodag.readthedocs.io/en/latest/api_reference/utils.html#eodag.utils.ProgressCallback), i.e. no `disable`?)
> - 'desc',
> -  'max_size',
> - 'pb',
> -  'position',
> -  'reset',
> -  'unit',
> -  'unit_scale'
All the documented parameters should be available

> 5.
> Also tried:
```py
from tqdm.notebook import tqdm

pg = ProgressCallback(tqdm(disable=True))

dag.download(all_products[0], progress_callback=pg)
```
This should also print the progress bar. The `disable=True` option should be used this way:
```py
pg = ProgressCallback(disable=True)
dag.download(all_products[0], progress_callback=pg)
```
This will not display the progress bar.

Some documentation on progress bars is available on https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/7_download.html#Progress-bar

**Comment by maximlamare** [comment]
@sbrunato I appreciate that you took the time to answer me.  I knew it would be some sort of PEBKAC issue :)

I'm sorry I hadn't realised that I was reading a different version of the documentation: I arrived to the docs via the [GitHub page](https://github.com/CS-SI/eodag) and didn't think of checking the version. I will switch to the develop branch for my purpose, since `tqdm` doesn't play nice with my notebook.
