### ISSUE TITLE
STAC REST API using docker-compose up

### ISSUE THREAD

**Issue by pedringcoding** [CS-SI/eodag#322]
Hello,

**Describe**
Failed to up the stac server app using docker compose with respect to the tutorial
```
git clone https://github.com/CS-SI/eodag.git
cd eodag
docker-compose up
```
Additionally, I have tried including the build step, but I have the same result.
```
git clone https://github.com/CS-SI/eodag.git
cd eodag
docker-compose build
docker-compose up
```

**To Reproduce**
CLI commands executed by windows 10 to reproduce the bug:
Follow steps by default tutorial exposed in readme.md

**Output**
At the commande line tool displayed:
```
stac_server | standard_init_linux.go:228: exec user process caused: no such file or directory
stac_server exited with code 1
```

**Environment:**
 - Python version: `3.8.5`
 - EODAG version: `2.3.1`

Thanks for all!

**Comment by sbrunato** [comment]
Hello @pedringcoding and thanks for reporting this issue.

Can you please update the code and checkout the `docker_windows` branch, to see if it works better:
```sh
cd eodag
git pull
git checkout docker_windows
```
Run `docker-compose` using recently added verbose mode for `stac-server`:
```sh
docker-compose build
EODAG_LOGGING=3 docker-compose up
```
And post the output here.
Thanks

**Comment by pedringcoding** [comment]
Hello @sbrunato, thank your team for all this work!

When I following indicated steps, get the next logs by command line:

For **docker-compose build**

WARNING: The EODAG_LOGGING variable is not set. Defaulting to a blank string.
Building browser
[+] Building 6.0s (15/15) FINISHED
 => [internal] load build definition from stac-browser.dockerfile                                                                                          0.1s
 => => transferring dockerfile: 653B                                                                                                                       0.0s
 => [internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/node:lts-buster-slim                                                                                    5.5s
 => [internal] load metadata for docker.io/library/nginx:stable-alpine                                                                                     5.7s
 => [auth] library/node:pull token for registry-1.docker.io                                                                                                0.0s
 => [auth] library/nginx:pull token for registry-1.docker.io                                                                                               0.0s
 => [build-stage 1/6] FROM docker.io/library/node:lts-buster-slim@sha256:12e2d4e68982ea48a4e5a865987f8aacbb1a5767a346f1279f676ef0f72c8cd2                  0.0s
 => [production-stage 1/2] FROM docker.io/library/nginx:stable-alpine@sha256:7b801536219e8b3a5dcaf0c5a34c4d4d0514e648905c83105d98c56740eb4f07              0.0s
 => CACHED [build-stage 2/6] RUN apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install -y git                                               0.0s
 => CACHED [build-stage 3/6] RUN git clone https://github.com/radiantearth/stac-browser.git                                                                0.0s
[+] Building 64.9s (19/19) FINISHED
 => [internal] load build definition from stac-server.dockerfile                                                                                           0.1s
 => => transferring dockerfile: 1.99kB                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/python:3.9-slim                                                                                         3.2s
 => [auth] library/python:pull token for registry-1.docker.io                                                                                              0.0s
 => [ 1/14] FROM docker.io/library/python:3.9-slim@sha256:2c018e29a8eada75e855d78641adda978a2c0a035fd928e281e1240144e8a337                                 0.0s
 => [internal] load build context                                                                                                                          0.1s
 => => transferring context: 26.43kB                                                                                                                       0.0s
 => CACHED [ 2/14] RUN apt-get update     && apt-get upgrade -y                                                                                            0.0s
 => CACHED [ 3/14] RUN echo UTC > /etc/timezone &&     apt-get install -y tzdata &&     rm /etc/localtime &&     ln -snf /usr/share/zoneinfo/UTC /etc/loc  0.0s
 => CACHED [ 4/14] RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y locales                                                         0.0s
 => CACHED [ 5/14] RUN sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen &&     dpkg-reconfigure --frontend=noninteractive locales &&   0.0s
 => [ 6/14] COPY setup.py setup.py                                                                                                                         0.0s
 => [ 7/14] COPY setup.cfg setup.cfg                                                                                                                       0.0s
 => [ 8/14] COPY README.rst README.rst                                                                                                                     0.1s
 => [ 9/14] COPY ./eodag /eodag                                                                                                                            0.1s
 => [10/14] RUN python setup.py install                                                                                                                   58.4s
 => [11/14] COPY ./docker/run-stac-server.sh /eodag/run-stac-server.sh                                                                                     0.1s
 => [12/14] RUN chmod +x /eodag/run-stac-server.sh                                                                                                         0.4s
 => [13/14] RUN addgroup --system user     && adduser --system --group user                                                                                0.6s
 => exporting to image                                                                                                                                     1.6s
 => => exporting layers                                                                                                                                    1.5s
 => => writing image sha256:6d5887bcad054241e92b23f03837013c7b4ba9ce4fe488f9e48fbdb65d832e0a                                                               0.0s
 => => naming to docker.io/library/eodag_stac                                                                                                              0.0s

I needed include _.env_ file to add argument _EODAG_LOGGING=3_

For **docker-compose config**

networks:
  eodag-stac-network:
    driver: bridge
services:
  browser:
    build:
      context: D:\pfernandezc\Projects\OnEO\TPI\workspace\pet-project\eodag
      dockerfile: docker/stac-browser.dockerfile
    container_name: stac_browser
    networks:
      eodag-stac-network: null
    ports:
    - published: 5001
      target: 80
    restart: unless-stopped
  stac:
    build:
      context: D:\pfernandezc\Projects\OnEO\TPI\workspace\pet-project\eodag
      dockerfile: docker/stac-server.dockerfile
    container_name: stac_server
    environment:
      EODAG_LOGGING: '3'
    networks:
      eodag-stac-network: null
    ports:
    - published: 5000
      target: 5000
    restart: unless-stopped
version: '3.7'

For **docker-compose up**

Creating stac_browser ... done
Creating stac_server  ... done
Attaching to stac_server, stac_browser
stac_browser | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
stac_browser | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
stac_browser | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
stac_server | /eodag/run-stac-server.sh: line 2: $'\r': command not found
stac_server | /eodag/run-stac-server.sh: line 4: $'\r': command not found
stac_server | /eodag/run-stac-server.sh: line 15: syntax error: unexpected end of file
stac_browser | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
stac_browser | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
stac_browser | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
stac_browser | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
stac_browser | /docker-entrypoint.sh: Configuration complete; ready for start up
stac_browser | 2021/07/21 12:13:41 [notice] 1#1: using the "epoll" event method
stac_browser | 2021/07/21 12:13:41 [notice] 1#1: nginx/1.20.1
stac_browser | 2021/07/21 12:13:41 [notice] 1#1: built by gcc 10.2.1 20201203 (Alpine 10.2.1_pre1)
stac_browser | 2021/07/21 12:13:41 [notice] 1#1: OS: Linux 5.10.25-linuxkit
stac_browser | 2021/07/21 12:13:41 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
stac_browser | 2021/07/21 12:13:41 [notice] 1#1: start worker processes
stac_browser | 2021/07/21 12:13:41 [notice] 1#1: start worker process 32
stac_browser | 2021/07/21 12:13:41 [notice] 1#1: start worker process 33
stac_server exited with code 0
stac_server | /eodag/run-stac-server.sh: line 2: $'\r': command not found
stac_server | /eodag/run-stac-server.sh: line 4: $'\r': command not found
stac_server | /eodag/run-stac-server.sh: line 15: syntax error: unexpected end of file
stac_server | /eodag/run-stac-server.sh: line 2: $'\r': command not found
stac_server | /eodag/run-stac-server.sh: line 4: $'\r': command not found
stac_server | /eodag/run-stac-server.sh: line 15: syntax error: unexpected end of file
stac_server | /eodag/run-stac-server.sh: line 2: $'\r': command not found
stac_server | /eodag/run-stac-server.sh: line 4: $'\r': command not found
stac_server | /eodag/run-stac-server.sh: line 15: syntax error: unexpected end of file
Exception in thread Thread-7:
Traceback (most recent call last):
  File "docker\api\client.py", line 268, in _raise_for_status
  File "requests\models.py", line 941, in raise_for_status
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localnpipe/v1.41/containers/cbb8fa39835d98dcda7252338e98d1dbd640636209f347e88abccafc776bfe89/attach?logs=0&stdout=1&stderr=1&stream=1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 950, in _bootstrap_inner
  File "threading.py", line 888, in run
  File "compose\cli\log_printer.py", line 224, in watch_events
  File "compose\container.py", line 202, in attach_log_stream
  File "compose\container.py", line 294, in attach
  File "docker\utils\decorators.py", line 19, in wrapped
  File "docker\api\container.py", line 62, in attach
  File "docker\api\client.py", line 405, in _read_from_socket
  File "docker\api\client.py", line 318, in _get_raw_response_socket
  File "docker\api\client.py", line 270, in _raise_for_status
  File "docker\errors.py", line 19, in create_api_error_from_http_exception
  File "requests\models.py", line 881, in json
  File "requests\models.py", line 829, in content
  File "requests\models.py", line 751, in generate
  File "urllib3\response.py", line 575, in stream
  File "urllib3\response.py", line 518, in read
  File "http\client.py", line 458, in read
  File "http\client.py", line 502, in readinto
  File "docker\transport\npipesocket.py", line 211, in readinto
  File "docker\transport\npipesocket.py", line 20, in wrapped
RuntimeError: Can not reuse socket after connection was closed.
stac_server exited with code 2

If you need more information or execute other steps, pleace, tell me.

One more time, thanks!

**Comment by sbrunato** [comment]
- Can you try again after having updated `docker_windows` branch ?

- Also, I see in your output 
> stac_server | /eodag/run-stac-server.sh: line 2: $'\r': command not found

which is strange as there should not be any `\r` character in this file. Could you try to open `docker/run-stac-server.sh` and replace CRLF EOL characters with LF. This can be done using Notepad++ (From the "Edit" menu, select "EOL Conversion" -> "UNIX/OSX Format"), or by running:
```sh
sed -i 's/\r//g' run-stac-server.sh 
```
Thanks

**Comment by sbrunato** [comment]
Another update, I added a `.gitattributes` file containing `* -text` to prevent git from normalizing EOL when running on windows

**Comment by pedringcoding** [comment]
Great!

I using the last changes included in docker_window feature, and its correctly running.

I can check the API exposed from _stac_server_. 

Thated really nice of you @sbrunato 
Thanks you very much!
