### ISSUE TITLE
This provider is not recognised by eodag: wekeo

### ISSUE THREAD

**Issue by carolinepacheco** [CS-SI/eodag#332]
Hi,

When I do: ``dag.set_preferred_provider(PROVIDER.lower())``
I got the following error: ``This provider is not recognised by eodag: wekeo``

I would like to know if the wekeo provider has been removed from version 2.3.1?

**Comment by sbrunato** [comment]
Hello @carolinepacheco , yes wekeo has been completely removed from the providers list with #295. This was released in `2.3.0b1`.
This provider was deprecated from a long time ago, and never got more than a partial support in eodag. 
See also #57: even using the latest HDA API, too few metadata were available (lacks of product geometry, ...)

**Comment by carolinepacheco** [comment]
Hi @sbrunato 

Ok. Thank you so much for your reply.
