### ISSUE TITLE
Search by id error with eodag latest release

### ISSUE THREAD

**Issue by Fahdben** [CS-SI/eodag#334]
**Bug description**
I've upgraded EODAG version to 2.3.2 and my code using `dag.search` with a product id is generating an error.

**Code To Reproduce**
Here is the code to reproduce this bug 
```py
from eodag import EODataAccessGateway
dag = EODataAccessGateway()
dag.search(id="S2A_MSIL1C_20181024T111121_N0206_R137_T29SPB_20181024T132414", provider="creodias")
```
**Output**
```sh
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/test_eodag/.py38/lib/python3.8/site-packages/eodag/api/core.py", line 587, in search
    search_plugin = search_kwargs.pop("search_plugin")
KeyError: 'search_plugin'
```

**Environment:**
 - Python version: 3.8
 - EODAG version:2.3.2

**Additional context**
I've tested the same code with a previous version of eodag and it's working fine. Maybe i'm missing some changes in the API with the new version. Also tested the same code with another provider, same output.

Thanks a lot for your help!

**Comment by sbrunato** [comment]
Thanks for this report @Fahdben !
