### ISSUE TITLE
[AWS-based providers] Nested downloaded directory

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#383]
When downloading Sentinel-2 products from `earth search` (or any other AWS-based provider), it seems that Eodag creates nested directories, for example:
![2022-01-07_18h01_08](https://user-images.githubusercontent.com/67311115/148579522-533a8824-8afc-49b2-99db-bd55bda09c54.png)

Is it wanted ?

Environment:

    Python version: Python 3.7.12
    EODAG version: eodag (Earth Observation Data Access Gateway): version 2.3.4

**Comment by sbrunato** [comment]
Hello @remi-braun ,
> Is it wanted ?

Yes for the moment it is, but this behavior may be updated. See #251

**Comment by remi-braun** [comment]
Yes it would be great, in order to manage results for every provider in the same way 😄
