### ISSUE TITLE
Wrong type hint for kwargs

### ISSUE THREAD

**Issue by LoicViennois** [CS-SI/eodag#385]
**Describe the bug**
The type hint given for `kwargs` in methods `search` `search_all` `search_iter_page` `download` `download_all` of class `EODataAccessGateway` is `dict`, but should probably be something like `int | str | bool` in order to avoid IDEs complaining about types.

**Code To Reproduce**
```python
gateway = EODataAccessGateway()
results = gateway.search_all(
    productType='S2_MSI_L2A_MAJA',
    start="2021-09-01",
    end="2021-09-02"
)
gateway.download_all(results, outputs_prefix="output")
```

**Output**

![Screenshot_20220112_113442](https://user-images.githubusercontent.com/9892489/149126485-9161a533-2920-4397-b6c1-f4c8c631032f.png)

**Environment:**
 - Python version: 3.10.1
 - EODAG version: 2.3.4
 - IDE : PyCharm 2021.2.3

**Comment by sbrunato** [comment]
Thanks for reporting this issue @LoicViennois !
