### ISSUE TITLE
Add eodag stub package

### ISSUE THREAD

**Issue by savmickael** [CS-SI/eodag#387]
When I run mypy on a code which import eodag, it claims that  `Skipping analyzing "eodag": module is installed, but missing library stubs or py.typed marker`

It is related to this page : https://mypy.readthedocs.io/en/stable/stubs.html

So for the moment I add a type ignore in the mypy config file but it could be interesting to create the stub package for eodag

**Comment by sbrunato** [comment]
Thanks for this feature request @savmickael !
