### ISSUE TITLE
Deletion of archive (zip) files after downloading fails [ONDA]

### ISSUE THREAD

**Issue by iliion** [CS-SI/eodag#397]
I want to delete the zip files after downloading EOProducts from **Onda**.

In order to do that I used the flag `delete_archive` set to  true, but the files dont get deleted.

I tried to do it in the following ways:
 -  in the configuration file **eodag.yml** as `delete_archive: True`
 -  in the python script as : ``` os.environ["EODAG__ONDA__DOWNLOAD__DELETE_ARCHIVE"] = 'true' ```
 -  in the function **download_all** as ```download_all(products_to_download, wait=5, timeout=60, delete_archive='true')```
 

**[Source](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/7_download.html)**
 
 

**Environment:**
 - Python version: 3.7
 - EODAG version: latest

**Comment by sbrunato** [comment]
Hello @iliion , this feature (GH-358) will be available in the next incoming release. If you want to test it before, you can install eodag from the develop branch using
```
pip install git+https://github.com/CS-SI/eodag.git@develop#egg=eodag
```
