### ISSUE TITLE
Shapefiles Download

### ISSUE THREAD

**Issue by tiqvahub** [CS-SI/eodag#422]
This may not be the appropriate place to make this question, but I wonder if someone could point me the shapefiles mentioned in this [tutorial](https://eodag.readthedocs.io/en/latest/notebooks/tutos/tuto_ship_detection.html) "Download the auxiliary files [here](https://github.com/CS-SI/eodag/tree/master/examples/auxdata/) which contain the appropriate shapefiles"

**Comment by sbrunato** [comment]
thank you @tiqvahub for reporting this deadlink. The fixed link should point to https://github.com/CS-SI/eodag/tree/master/docs/notebooks/tutos/auxdata

We'll have to update the documentation to fix it

**Comment by tiqvahub** [comment]
Thank you @sbrunato for reply. I appreciated your time.
