### ISSUE TITLE
WARNING when downloading with earth_search

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#423]
I get all the time the same warning when downloading with `earth_search` provider:

```
2022-03-14 16:16:59 - [WARNING] - Unexpected error: An error occurred (InvalidBucketName) when calling the ListObjects operation: The specified bucket is not valid.
2022-03-14 16:16:59 - [WARNING] - Skipping v0//collections/sentinel-s2-l2a/items/S2A_32TLT_20220213_0_L2A
```

Do you know from where it comes from ? Is it from my configuration ?

Environment:

    Python version: Python 3.7.12
    EODAG version: eodag (Earth Observation Data Access Gateway): version 2.4.0

**Comment by sbrunato** [comment]
Hello @remi-braun , I tried performing a search on `earth_search` +`S2_MSI_L2A` using temporal & geometric query arguments, and also directly on id `S2A_32TLT_20220213_0_L2A`, then download. Both worked well.

Can you post a code snippet to help us reproduce the bug ? 
Thank you

**Comment by remi-braun** [comment]
Ok this comes from me, I wasn't copying the `assets` field during conversion from/to geojsons.

My bad 😅

**Comment by remi-braun** [comment]
Sorry to bother again on the same subject, but on some product, I still get this warning.

It comes from the line 257 (`complementary_url_key`) from `aws.py`, where I get:
```python
for complementary_url_key in product_conf.get("complementary_url_key", []):
    print(
        self.get_bucket_name_and_prefix(
            product, product.properties[complementary_url_key]
        )
    )
    
('v0', '/collections/sentinel-s2-l2a/items/S2A_32TLT_20211016_0_L2A')
('sentinel-s2-l2a', 'tiles/32/T/LT/2021/10/16/0')
```

The productPath seems to be the problem:
```python
print(
    self.get_bucket_name_and_prefix(
        product, product.properties["productPath"]
    )
)
    
('v0', '/collections/sentinel-s2-l2a/items/S2A_32TLT_20211016_0_L2A')
```

The assets are all fine, they all point to the correct bucket.

With the product conf :
![2022-03-16_09h02_50](https://user-images.githubusercontent.com/67311115/158543880-552db726-eb5e-448a-b369-15ec5b218a28.png)

I have trouble reproducing exactly this issue, do I will just display the content of the product, could you indicate me if sth is off inside ?

![2022-03-16_09h09_22](https://user-images.githubusercontent.com/67311115/158545259-8984d270-4804-4a7a-8cea-7ffe6d148a32.png)

Thansk a lot 🙏

**Comment by remi-braun** [comment]
> 

It seems that the fact that ProductPath is empty is related to this "false" bucket and the non existing manifest.safe file.
Herunder is the log for OK/NOK products:
![2022-03-16_09h23_49](https://user-images.githubusercontent.com/67311115/158547474-d6050220-4f49-4fac-9c57-ff8fea8063be.png)
