### ISSUE TITLE
EOProduct object does not include the `pseudopath` key:value pair

### ISSUE THREAD

**Issue by konstantinos2018** [CS-SI/eodag#439]
**Describe the bug**
Hi, I'm not sure if this is a bug or is done on purpose. When using the ONDA DIAS as a provider and searching for products, I expect to have the `pseudopath` key in the properties attribute of each EOProduct object. Below I give the example with `eodag` and the equivalent using `requests`.

**Code To Reproduce**
*Example with `eodag`*
```python
from eodag import EODataAccessGateway
from eodag import setup_logging

dag = EODataAccessGateway()
setup_logging(3)

coords = [11.67213780488836, 45.62114753968596, 11.747695565368888, 45.69241119821032]
search_results, total_count = dag.search(
    productType='S2_MSI_L1C',
    geom=coords,
    start='2021-12-13',
    end='2021-12-30',
    raise_errors=True,
    cloudCover=60
)

for item in search_results[0].properties.keys():
    if 'pseudo' in item:
        print(item)
```
*Example with `requests`*
```python
import requests

api_url = 'https://catalogue.onda-dias.eu/dias-catalogue/Products?productType=S2MSI1C&$format=json&$search=%22footprint:%22Intersects%28POLYGON%20%28%2811.6721%2045.6211%2C%2011.6721%2045.6924%2C%2011.7477%2045.6924%2C%2011.7477%2045.6211%2C%2011.6721%2045.6211%29%29%29%22%20AND%20productType:S2MSI1C%20AND%20cloudCoverPercentage:[0%20TO%2060]%20AND%20beginPosition:[2021-12-13T00:00:00.000Z%20TO%20%2A]%20AND%20endPosition:[%2A%20TO%202021-12-30T00:00:00.000Z]%22&$top=20&$skip=0'
response = requests.get(api_url)
data = response.json()

for item in data['value'][0].keys():
    if 'pseudo' in item:
        print(item)
```
**Output**
In the first (`eodag`) case I  get no output from the `print` statement. In the second (`requests`) case I get a key (`str`) related to the `pseudopath` of the product, as expected.

**Environment:**
 - Python version: `Python 3.10.4`
 - EODAG version: `version 2.4.0`

**Additional context**
If this "functionality" is in fact not implemented, is there some kind of "quick fix" that I can apply myself?

**Comment by sbrunato** [comment]
Hello @konstantinos2018 , thanks for submitting this issue. I just updated `develop` branch with a fix. You should now get `pseudopath` in `EOProduct.properties`.

To use it before a new version is released on pypi, you can install it using 
```sh
pip install git+https://github.com/CS-SI/eodag.git@develop
```

**Comment by konstantinos2018** [comment]
@sbrunato Hi Sylvain, I highly appreciate your fast response! Thank you :)
