### ISSUE TITLE
move external python apis and server to extras_require

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#461]
Get external python apis out of `install_requires` (`usgs`, `ecmwf-api-client`), in order to keep `eodag` core as light as possible. Also move server mode the same way.

Raise a well formatted error message if the external api is needed:
```
Access to ECMWF data requires the installation of an additional library.
Please install it via pip install ecmwf-api-client`.
```
And add the "complete" `extras_require`, giving the ability to install these external python apis with `pip install eodag[complete]` (also available in `eodag[dev]`)

**Comment by avalentino** [comment]
This could be indeed a good idea, especially considering that the status of the maintenance upstream package `usgs` is not totally clear at the moment. It could be unmaintained (see kapadia/usgs#38).
