### ISSUE TITLE
Add S2_MSI_L1C productType to the USGS provider

### ISSUE THREAD

**Issue by vidlb** [CS-SI/eodag#487]
When trying to download Sentinel2 images using the USGS provider, the "S2_MSI_L1C" product type is not recognized, even though it is available using the earth explorer website.

It would be great to add this one (and more precisely in my case I'd like that because I only got a bunch of failure when trying to do that using the peps provider...).

**Comment by sbrunato** [comment]
@vidlb you can also try using one of the following providers, already configured with `S2_MSI_L1C`:
```py
>>> dag.available_providers("S2_MSI_L1C")
['astraea_eod', 'aws_eos', 'creodias', 'earth_search', 'earth_search_gcs', 'mundi', 'onda', 'peps', 'sobloo']
```

**Comment by vidlb** [comment]
@sbrunato , thanks for the suggestion, but I miss credentials, is any of these service is free of charge ?

**Comment by sbrunato** [comment]
> @sbrunato thanks for the suggestion, but I miss credentials, is any of these service is free of charge (other than peps) ?

- `creodias`, `mundi`, `onda`, `peps`, `sobloo` are free, you just need to register
- for `earth_search_gcs` you need credentials for google cloud storage
- for `astraea_eod`, `aws_eos`, `earth_search` you need to pay using AWS credentials 

For more details, see [provider registration documentation](https://eodag.readthedocs.io/en/stable/getting_started_guide/register.html)
