### ISSUE TITLE
Creodias download not working

### ISSUE THREAD

**Issue by ds2268** [CS-SI/eodag#547]
**Describe the bug**
Creodias download is not working.

**Code To Reproduce**

`rnd_product.get_quicklook(base_dir=sample_folder_out)`

**Output**

`ReadTimeoutError: HTTPSConnectionPool(host='identity.cloudferro.com', port=443): Read timed out. (read timeout=5)`

**Environment:**
 - Python version: 3.9.0
 - EODAG version: 2.6.0

**Additional context**

I have opened a support ticket with Creodias, if the problem is on their side. The current response is:

`We will find out if there have been any changes to the API.`

**Comment by ds2268** [comment]
Additional response from the Creodias support:

"The timeout is only set for 5 seconds, the problem could be caused by network problems on our infrastructure.
Unfortunately, there is not much we can do about this, temporary delays can occur and that is why these timeouts occur.
In this case, we may recommend changing the timeout to a larger value or use a try/except clause.
However, if the problem occurs on all attempts, please request a piece of code to analyze the problem."

We should implement a proper retry strategy for the API calls, something along this direction:

```
    retry_strategy = Retry(total=10,
                           status_forcelist=[429, 500, 502, 503, 504],
                           method_whitelist=whitelist,
                           backoff_factor=1)
```

**Comment by sbrunato** [comment]
Hello @ds2268, if you want to temporarily change the timeout value for auth with creodias, you can do it with:
```py
import eodag.plugins.authentication.keycloak
eodag.plugins.authentication.keycloak.HTTP_REQ_TIMEOUT = <your_value>
```
For your issue, please also check that your credentials are set, see [configuration doc](https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/1_overview.html#Configure).

Please also post a longer code to reproduce and a longer output with the traceback and logs with high verbosity (`setup_logging(3)`, see [logging doc](https://eodag.readthedocs.io/en/stable/notebooks/api_user_guide/3_configuration.html#Logging).
Thanks.

**Comment by ds2268** [comment]
Today it's working again. I guess it's really Creodias infrastructure and timeouts. I will close the issue for now and re-open it, if the problem persists.
