### ISSUE TITLE
NotAvailableError: No usgs request url was found for LC08_L1TP_197030_20140926_20200911_02_T1

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#565]
_Originally posted by @tvoirand in https://github.com/CS-SI/eodag/issues/560#issuecomment-1330362096_

The search also works fine, however, I am getting an error when downloading product `LC08_L1TP_197030_20140926_20200911_02_T1`.

```
eodag.utils.exceptions.NotAvailableError: No usgs request url was found for LC08_L1TP_197030_20140926_20200911_02_T1
```

`setup_logging(3)` gives me this download url: `https://earthexplorer.usgs.gov/download/external/options/landsat_ot_c2_l1/LC81970302014269LGN01/M2M/`.

I am able to download products for more recent dates (for example 20221017) on the same AOI. But I am also able to download the 20140926 product with another library. Is there any limitations to the time range that eodag can access, or am I missing another parameter to access older products?

Please let me know for any other information that could be useful.

**Comment by sbrunato** [comment]
> I am also able to download the 20140926 product with another library

@tvoirand what library are you using to download this product ?

**Comment by tvoirand** [comment]
I am using [landsatxplore](https://github.com/yannforget/landsatxplore), or to be precise [a fork of landsatxplore](https://github.com/tvoirand/landsatxplore/tree/earthexplorer_fix), because it seems this library is not maintained anymore.

**Comment by sbrunato** [comment]
Using your [fork of landsatxplore](https://github.com/tvoirand/landsatxplore/tree/earthexplorer_fix) I also have the same not available error:
```
$ landsatxplore search --dataset landsat_ot_c2_l1  --start 2014-09-26 --end 2014-09-27
LC08_L1GT_003004_20140927_20200911_02_T2
LC08_L1TP_003005_20140927_20200910_02_T2
LC08_L1GT_003006_20140927_20200910_02_T2
LC08_L1TP_003007_20140927_20200911_02_T1
LC08_L1TP_003008_20140927_20200910_02_T1
LC08_L1GT_003009_20140927_20200911_02_T2
[...]

$ landsatxplore download LC08_L1TP_197030_20140926_20200911_02_T1
Traceback (most recent call last):
  File "/home/sylvain/.virtualenvs/landsatxplore/bin/landsatxplore", line 8, in <module>
    sys.exit(cli())
  File "/home/sylvain/.virtualenvs/landsatxplore/lib/python3.10/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/sylvain/.virtualenvs/landsatxplore/lib/python3.10/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/sylvain/.virtualenvs/landsatxplore/lib/python3.10/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sylvain/.virtualenvs/landsatxplore/lib/python3.10/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sylvain/.virtualenvs/landsatxplore/lib/python3.10/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/sylvain/.virtualenvs/landsatxplore/lib/python3.10/site-packages/landsatxplore/cli.py", line 164, in download
    fname = ee.download(
  File "/home/sylvain/.virtualenvs/landsatxplore/lib/python3.10/site-packages/landsatxplore/earthexplorer.py", line 146, in download
    filename = self._download(url, output_dir, timeout=timeout, skip=skip)
  File "/home/sylvain/.virtualenvs/landsatxplore/lib/python3.10/site-packages/landsatxplore/earthexplorer.py", line 88, in _download
    raise EarthExplorerError(error_msg)
landsatxplore.errors.EarthExplorerError: Download is not available
```
Do you have a working code snippet to download `LC08_L1TP_197030_20140926_20200911_02_T1` ?

**Comment by tvoirand** [comment]
Thanks a lot for your investigation.

Here is a python code snippet that I am using (needs replacing "XXX"):

```python
from landsatxplore.api import API
from landsatxplore.earthexplorer import EarthExplorer

landsatxplore_api = API("XXX", "XXX")
earthexplorer_catalog = EarthExplorer("XXX", "XXX")

scenes = landsatxplore_api.search(
    dataset="landsat_ot_c2_l1",
    bbox=(3.4314538515220647, 43.257483919751735, 3.8428533965849567, 43.484636696164415),
    start_date="2014-09-25",
    end_date="2014-09-27",
)

for scene in scenes:
    earthexplorer_catalog.download(scene["entity_id"], output_dir="XXX")
```

But I just noticed that the downloaded file is actually "LC08_L1TP_197030_20140926_20170419_**01**_T1.tar.gz", and contains collection 1 data, even though the IDs landsatxplore returns are:
`display_id`: `LC08_L1TP_197030_20140926_20200911_02_T1`
`landsat_product_id`: `LC08_L1TP_197030_20140926_20200911_02_T1`
`entity_id`: `LC81970302014269LGN01`
`landsat_scene_id`: `LC81970302014269LGN01`

Could this be what is causing the error with the CLI command that you used and with EODAG?

I need to check if using collection 1 data causes problem for my usage, even though I requested collection 2 data.

**Comment by sbrunato** [comment]
That's it, in your example `landsatxplore` downloads C1 data which is also downloadable using `eodag`.

That is because you did not specify a `dataset` when using  `earthexplorer_catalog.download()`, and internally the method runs `landsatxplore.util.guess_dataset(scene["entity_id"])` which returns `landsat_8_c1`.

If you try:
```py
earthexplorer_catalog.download(scene["entity_id"], dataset="landsat_ot_c2_l1", output_dir="XXX")
```
You'll get
```
landsatxplore.errors.EarthExplorerError: Download is not available
```

**Comment by tvoirand** [comment]
Thank you for your investigation and resolution !
