### ISSUE TITLE
Create WEKEO DIAS drivers

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#57]
**[Original report](https://bitbucket.org/geostorm/eodag/issue/57) by Oyono (Bitbucket: [aoyono](https://bitbucket.org/aoyono), GitHub: [aoyono](https://github.com/aoyono)).**

----------------------------------------

https://www.wekeo.eu/

**Comment by sbrunato** [comment]
Update CSW plugin (see if #94 is needed) and finalize wekeo provider integration

**Comment by maximlt** [comment]
Currently, search with wekeo is implemented with the CSW search plugin.

Some research has shown that:
* The [CSW endpoint](https://wekeo.eu/guide-catalogue-service-for-web-wekeo-csw) offered by wekeo only allows to get access to the collections metadata, not to the products themselves. [This request](https://pn-csw.apps.mercator.dpi.wekeo.eu/elastic-csw/service?service=CSW&request=GetRecords&version=2.0.2&resultType=hits), for instance, shows that wekeo offers 232 collections.
* wekeo offers now a REST Api called [Harmonised Data Access API](https://wekeo.eu/web/guest/hda-api). It has an open-source client [hda](https://github.com/ecmwf/hda) developed by the ECMWF.
* Some scripts and notebooks, available online, show how to use the HDA API ([here](https://gitlab.eumetsat.int/eumetlab/atmosphere/atmosphere/-/blob/master/10_data_access/12_WEkEO_harmonized_data_access_api.ipynb) and [here](https://gitlab.eumetsat.int/eumetlab/atmosphere/atmosphere/-/blob/master/10_data_access/hda_api_functions.ipynb)) The functions used in the 2nd notebook can be found in wekeo's Jupyter Hub (Sign in -> Dashboard -> JupyterHub)
* The package [eo_harvest](https://gitlab.ifremer.fr/naiad/eo_harvest) uses the HDA API of wekeo to [search and download](https://gitlab.ifremer.fr/naiad/eo_harvest/-/blob/master/eo_harvest/stores/wekeo.py) products
* wekeo requires a token to access to its HDA API, once generated it is valid for 1 hour only.

Wekeo's search plugin won't rely on the CSW plugin anymore (which will still stay around), it will instead rely on the HDA API.

**Comment by sbrunato** [comment]
> By the use of HDA API , in particular the querymetadata, you can see the list of parameters to use for product request. After that no metadata on a product instance is given due to the fact that this interface has for objective to standardize the request and some metadata are not available on all products (ie. CMEMS or Land)

For example, the only metada available for a given `S1_SAR_GRD` product is:
```json
 {
      "downloadUri": null,
      "filename": "S1B_IW_RAW__0SDV_20200110T174650_20200110T174723_019758_0255B5_F9FC.SAFE",
      "order": null,
      "productInfo": {
        "datasetId": "EO:ESA:DAT:SENTINEL-1:SAR",
        "product": "S1B_IW_RAW__0SDV_20200110T174650_20200110T174723_019758_0255B5_F9FC.SAFE",
        "productEndDate": "2020-01-10T17:47:23.200000Z",
        "productStartDate": "2020-01-10T17:46:50.800000Z"
      },
      "size": 1672255055,
      "url": "040ff724-6884-5366-ac68-eb96a78d2c4f/S1B_IW_RAW__0SDV_20200110T174650_20200110T174723_019758_0255B5_F9FC.SAFE"
    },
```
