### ISSUE TITLE
Add support for more Sentinel 3 data products

### ISSUE THREAD

**Issue by catchSheep** [CS-SI/eodag#575]
**Is your feature request related to a problem? Please describe.**
Some providers (like [SARA](https://copernicus.nci.org.au/sara.client/)) allow for more product types than described in the default product_types.yml.
As far as I can tell these are mostly just Sentinel 3 product types, eg Water products (OLCI_WFR etc, LSTR WST), SLSTR_AOD, SLSTR_FRP, and SYNERGY products (eg SYN Surface reflectance, AOD, Vegetation V10 & Vg1.
When adding one of these providers, it's a bit more of a headache otherwise, needing to specify an external cfg file with `EODAG_EXT_PRODUCT_TYPES_CFG_FILE `

**Describe the solution you'd like**
Add these product types into the product_types.yml default config. eg compare the current [file](https://github.com/CS-SI/eodag/blob/develop/eodag/resources/product_types.yml#L741) to one I've changed [here](https://github.com/AustralianSDAF/eodag-Australia/blob/develop/eodag/resources/product_types.yml#L741) (NB: S3 products are also sorted by instrument in the new one, & remove the erroneous "L2" tag from S3_ERR)

**Describe alternatives you've considered**
Could just leave it to the user, unless issue #14 is considered.

**Additional context**
This is mostly related to adding SARA to EODAG, a related issue is [https://github.com/CS-SI/eodag/issues/14](https://github.com/CS-SI/eodag/issues/14)

**Comment by sbrunato** [comment]
Hello @catchSheep , and many thanks for these suggestions! 
Would you mind opening a Pull Request from your fork to add both product types update and SARA provider? https://github.com/CS-SI/eodag/compare/develop...AustralianSDAF:eodag-Australia:develop
That would be a great input.
Thanks

Also related to #168

**Comment by catchSheep** [comment]
No worries. Pull request is: https://github.com/CS-SI/eodag/pull/578
