### ISSUE TITLE
Message rate exceeded - downloading in Jupyter

### ISSUE THREAD

**Issue by catchSheep** [CS-SI/eodag#608]
**Bug Description**
When downloading a product through eodag in jupyter, if ones download speed is too high (eg 70MB/s) the log at versoity=2 will be:
```
2023-01-17 08:51:28,917 eodag.plugins.download.base      [INFO    ] Download url: <url>
IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)

... (more messages about the message rate being exceeded)
```
This only occurs on a machine with a ~70MB/s (~560MBit/s) connection to the repo, machines with only ~10MB/s don't seem to get the issue.  

**Code To Reproduce**

Within a jupyter notebook, and **with sufficient network speed** to your chosen provider:
```py
from eodag import EODataAccessGateway
from eodag import setup_logging

setup_logging(verbose=2)

dag = EODataAccessGateway()

dag.set_preferred_provider("sara")

bounds = [122,-17, 126,-19]
geo = {"lonmin": bounds[0], "latmin": bounds[1], "lonmax": bounds[2], "latmax": bounds[3]}
search_criteria = {
    "productType": "S1_SAR_GRD",
    "start": "2022-12-20",
    "end": "2023-03-01",  
    "sensorMode": "IW",
    "geom": geo
}

search_results = dag.search_all(**search_criteria)

search_results[0].download()
```

**Output**
The download occurs, and the progress bar goes up, but occasionally stops and the message:
```
IOPub message rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_msg_rate_limit`.

Current values:
ServerApp.iopub_msg_rate_limit=1000.0 (msgs/sec)
ServerApp.rate_limit_window=3.0 (secs)
```
will be printed to the log. Everything else occurs normally.

**Environment:**
 - Python version: 3.10.8
 - EODAG version: 2.7.1.dev25+gb5486f7 (should be the latest on develop or close to it )
 Other packages from `jupyter --version`
  ```
IPython          : 8.8.0
ipykernel        : 6.20.2
ipywidgets       : 8.0.4
jupyter_client   : 7.4.9
jupyter_core     : 5.1.3
jupyter_server   : 2.1.0
jupyterlab       : 3.5.2
nbclient         : 0.7.2
nbconvert        : 7.2.8
nbformat         : 5.7.3
notebook         : 6.5.2
qtconsole        : 5.4.0
traitlets        : 5.8.1
```

**Additional context**
My guess is that this would be occurring from the tqdm update being related to miniters (possibly a default, relating to block size in downloading, if not otherwise set). ie if your speed is fast enough, you'll exceed 1000msgs per 3 seconds.  

If that is the issue, it could possibly be solved by:
 - Initialising tqdm with `mininterval=0.01` (updates 100x a second, should be basically imperceptible, while still being under 333/s) if the progress bar class interfacing with tqdm hasnt been given an override, or
 
Possibly also allowing a passthrough of something like 
```py
progress_bar_options = {
  eggs = spam1
  sausages = spam2
}
#Then either:
dag = EODataAccessGateway(progress_bar_options = progress_bar_options)
# or 
dag = EODataAccessGateway()
dag.set_progress_bar_options(progress_bar_options)
```
could be a solution?

**Comment by sbrunato** [comment]
Hello @catchSheep ,
can you try to customize `download()` progress bar using the following code ?
```py
from eodag.utils import ProgressCallback

custom_bar = ProgressCallback(mininterval=0.01)
search_results[0].download(progress_callback=custom_bar)
```
See [Download documentation / Progress bar](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/7_download.html#Progress-bar)

**Comment by catchSheep** [comment]
Thanks @sbrunato , but that doesnt seem to work, and results in the errors like normal.  As an example, try setting mininterval=2, or set miniters to something absurd. While one would expect 2 seconds per update, that does not seem to be the case. Even running your example in a script in terminal, it doesn't seem to respect mininterval or miniters. (although obviously wont give the jupyter errors)

With your example, I dont think the ProgressCallback object is being overwritten though. Progress_callback.mininterval is preserved after calling result.download(progress_callback=progress_callback), the only thing that is overwritten is "desc" (probably correctly, likely [here](https://github.com/CS-SI/eodag/blob/develop/eodag/api/product/_product.py#L310)?)

I see that ProgressCallback inherits from tqdm.auto.tqdm, so grabbing how the downloading seems to work in `eodag.plugins.download.http` the following does result interval of 2 seconds:
```py
import requests
from tqdm.auto import tqdm
from eodag.utils import ProgressCallback
        
progress_callback = ProgressCallback(mininterval=2)

url = "<direct link to a similarly sized file not needing authentication>"

stream = requests.get(url, stream=True)
total =  int(stream.headers['content-length'])        
progress_callback.reset(total=total)
with open('output.zip', "wb") as fhandle:
    for chunk in stream.iter_content(chunk_size=64*1024):
        size = fhandle.write(chunk)
        progress_callback.update(size)

progress_callback.update(total)
```
Setting it to `0.01` does not give the limit rate message, while having `mininterval=0.0005` does. The strange thing is that using `progress_callback = ProgressCallback()` by itself above does not give me the bloated log. It seems [tqdm by default ](https://github.com/tqdm/tqdm#Documentation) sets mininterval=0.1. This can be checked by:
```py
from eodag.utils import ProgressCallback

progress_callback = ProgressCallback()
print(progress_callback.mininterval)
```


I dont however see anywhere where mininterval or miniters is overwritten, so I'm scratching my head a bit here  (a search through the source for mininterval and miniters only gives `eodag.utils.__init__` , which only contains a comment listing each)

Just the same, 
```py
from eodag.utils import ProgressCallback

progress_callback = ProgressCallback()
print(progress_callback.mininterval)
print(progress_callback.mininterval)
```
prints out 0.1


For extra info:
- my tqdm is version '4.64.1'.
- looking in eodag.plugins.download.http, the `chunk size = 64*1024`, `(1000/s)*64*1024B ~= 66MB/s`, the approx speed that would seem like if you go over you would get this issue in jupyter (assuming 1000msgs/s is the limit)
- I can increase the message rate by launching jupyter with some special options, but there does seem to be a larger issue here
- Setting `chunk_size=1024*1024` at both locations[[1](https://github.com/CS-SI/eodag/blob/develop/eodag/plugins/download/http.py#L388), [2](https://github.com/CS-SI/eodag/blob/develop/eodag/plugins/download/http.py#L583)] in `eodag.plugins.download.http` also fixes the issue, but this may just be kicking the can down the road to about 1GB/s connections

**Comment by catchSheep** [comment]
Something that confuses me further, but that hopefully shines more of a light on what the issue may be, is that running:
```py
from eodag.utils import ProgressCallback

progress_callback = ProgressCallback(mininterval=2)
search_results[2].download(progress_callback=progress_callback, extract=False)
```
in one cell will create a progress bar that updates faster than every 2 seconds, and produces the message rate exceeded log messages as above.

Then using that same progress bar variable `progress_callback`  in another cell by straight the above after running:
```py
import requests
from eodag.utils import ProgressCallback
stream = requests.get(<similar url>, stream=True)
total =  int(stream.headers['content-length'])
progress_callback.reset(total=total)
with open('output.zip', "wb") as fhandle:
    for chunk in stream.iter_content(chunk_size=1*1024):
        size = fhandle.write(chunk)
        progress_callback.update(size)
```
modifies the (same) progress bar for the above cell, correctly only updating it with an interval of 2 seconds, and not producing message rate exceeded log messages.

Additionally, logging the values of `progress_callback.mininterval` and `progress_callback.miniters` inside of `HTTPDownload.download_request` while calling it with the above code gives the values 2 and 0, as expected

**Comment by sbrunato** [comment]
@catchSheep there was a non-customizable `refresh()` which has just been removed on `develop` branch. `mininterval` should now be at `tqdm` default value (0.1s), and should also be customizable
