### ISSUE TITLE
[Documentation][Enhancement] API__CREDENTIALS vs AUTH__CREDENTIALS__*

### ISSUE THREAD

**Issue by catchSheep** [CS-SI/eodag#618]
For people unfamiliar with EODAG, it may help to mention that authenticating for servers that use the API base class (eg USGS) need you to specify `EODAG__<PROVIDER>__API__CREDENTIALS__USERNAME` and so on, rather than `EODAG__<PROVIDER>__AUTH__CREDENTIALS__USERNAME` etc.
Regardless, the user would know that something has gone wrong, as the API will either be pruned or lack credentials to download.

**Describe the solution you'd like**
Perhaps a brief section below the current cell # 2 in [/notebooks/api_user_guide/1_overview.html](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/1_overview.html) mentioning this nuance. 
(or somewhere in [notebooks/api_user_guide/3_configuration.html](https://eodag.readthedocs.io/en/latest/notebooks/api_user_guide/3_configuration.html))

**Describe alternatives you've considered**
Authentication for API's could also be given in a more consistent manner. Eg if EODAG__USGS__API__CREDENTIALS__* does not exist, look for EODAG__USGS__AUTH__CREDENTIALS__*

Whether or not the alternate solution above  is considered (disregarding just listing this nuance in the documentation) would depend on whether you'd want a consistent way of authentication, or if there's good reason (from user and/or dev side) to keep them separate. The above change may also require refactoring quite a few functions other than the api itself that check if "api" is in the config, which may lower it on the priority list.
 eg in `EODataAccessGateway._prune_providers_list`, there is:
```py
conf = self.providers_config[provider]
if hasattr(conf, "api") and getattr(conf.api, "need_auth", False):
    # Prune this provider if "conf.api" has no `not None` "credentials" values
```

**Comment by sbrunato** [comment]
thanks for proposing this documentation update @catchSheep .

In [Getting started / configure EODAG](https://eodag.readthedocs.io/en/stable/getting_started_guide/configure.html#environment-variable-configuration), is described how to to update EODAG configuration using environment variables.

But you are right, we should also make it clearer how to use environment variables to update credentials for a provider that uses an API plugin. 

- [ ] Credentials set should be described for both providers using Auth plugin and API plugin in this [page](https://eodag.readthedocs.io/en/stable/getting_started_guide/configure.html#environment-variable-configuration)
