### ISSUE TITLE
readthedocs build failing

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#673]
Documentation build fails on readthedocs.org and returns the following error:
```
pandoc: Unknown extension: smart
```
See https://github.com/readthedocs/readthedocs.org/issues/10143

**Comment by mgeier** [comment]
You should update your RTD settings, see https://github.com/spatialaudio/nbsphinx/issues/720#issuecomment-1467799866.

**Comment by sbrunato** [comment]
> You should update your RTD settings, see [spatialaudio/nbsphinx#720 (comment)](https://github.com/spatialaudio/nbsphinx/issues/720#issuecomment-1467799866).

many thanks @mgeier !
