### ISSUE TITLE
peps storagestatus not set for new Sentinel-2 L1C products

### ISSUE THREAD

**Issue by opseasoi** [CS-SI/eodag#676]
**Describe the bug**
status for new S2-L1C products from PEPS don't match one of the disk/staging/tape value, but "tier2" so storageproperty property cannot be set.
With sentinelhub as provider it is OK. 

**Code To Reproduce**
>>> from eodag import EODataAccessGateway
>>> dag = EODataAccessGateway()
>>> search_criteria = {
...     "productType": "S2_MSI_L1C",
...     "start": "2023-03-08",
...     "end": "2023-12-01",
...     "geom": {"lonmin": 1, "latmin": 43, "lonmax": 2, "latmax": 44}
... }
>>> products_first_page, estimated_total_number = dag.search(**search_criteria)
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)
>>> 

**Output**
Could not extract property from tier2 using (?P<ONLINE>disk)|(?P<STAGING>staging)|(?P<OFFLINE>tape)

**Environment:**
 - Python version: Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
 - EODAG version: 2.7

**Additional context**
Add any other context about the bug here.

**Comment by sbrunato** [comment]
Hello @opseasoi and thank you for pointing out his issue. This will be fixed soon and integrated in the next release
