### ISSUE TITLE
product types aliases

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#692]
Use product types aliases (new field in `product_types.yml`) to be able to use a different name (`EO:ESA:DAT:EODC-SENTINEL-1:L1_GRD` instead of `S1_SAR_GRD`) pointing to the same product type.
Use this alias instead of default ID if defined in  `product_types.yml`

**Comment by leso-kn** [comment]
Changes so far pushed via 08f638d. Next steps:
- Utilitize new `[de]reference_product_type()` methods in places dealing with productTypes comprehensively
