### ISSUE TITLE
The port is missing in STAC API web page.

### ISSUE THREAD

**Issue by legendjslc** [CS-SI/eodag#718]
**Describe the bug**
When running the STAC API with 'eodag serve test', the service can run, but the link on the page is missing the specified port, resulting in the link pointing to the wrong website address.

**Code To Reproduce**
Start STAC REST API:
```sh
^C[ncdc@131 ~]$ eodag serve-rest -p 5000 &
[1] 216939
[ncdc@131 ~]$  * Serving Flask app 'eodag.rest.server'
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
```

**Output**

![222](https://user-images.githubusercontent.com/2969368/233941009-6440850e-345a-45a8-a81a-02ef2d20e25c.png)

**Environment:**
 - EODAG version: `2.10.0`

**Comment by sbrunato** [comment]
Hello @legendjslc , thanks for pointing out his issue. 
In order to help us reproduce this issue, can you please post how the redirection is performed from http://127.0.0.1:5000 to http://192.168.92.131:3200 ?

**Comment by legendjslc** [comment]
> Hello @legendjslc , thanks for pointing out his issue. In order to help us reproduce this issue, can you please post how the redirection is performed from http://127.0.0.1:5000 to http://192.168.92.131:3200 ?

centos 7.9, nginx.

`
server  {
    listen 3200;
    server_name 192.168.92.131 ;

     location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:5000;
    }
 
access_log /var/log/nginx/access.log;
   error_log /var/log/nginx/error.log;

`

**Comment by sbrunato** [comment]
Thanks for the configuration @legendjslc . 

EODAG STAC API migration to `fastapi` is in progress, see https://github.com/CS-SI/eodag/pull/701

Using the associated branch https://github.com/CS-SI/eodag/tree/fastapi or csspace/eodag-server:2.9.3.dev21-gff3a496 you will have support for the `X-Forwarded-Host` header that can be set in your `nginx.conf` with:
```
proxy_set_header X-Forwarded-Host $host:3200;
```
I do not think there is another standard header to define the port forwarding.

If this is ok for you, this feature will be available as is as soon as `fastapi` branch is merged (soon)

**Comment by legendjslc** [comment]
ok, thank you.
