### ISSUE TITLE
'packaging' distribution is missing from conda package

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#740]
**Describe the bug**

When installing a fresh environment with the conda `environment.yml.file`, I get the error : 
> pkg_resources.DistributionNotFound: The 'packaging' distribution was not found and is required by flasgger

I think your conda package is missing this library :)

**Code To Reproduce**

`>>>  conda env create -f environment.yml`

with the file : 

The file used is: 
```environment.yml
name: eodag_test
channels:
  - conda-forge
dependencies:
  - python=3.9
  - eodag
```

NB : I am using mamba solver
**Output**

> pkg_resources.DistributionNotFound: The 'packaging' distribution was not found and is required by flasgger

**Comment by sbrunato** [comment]
Hello @remi-braun and thanks submitting this issue. 
`flasgger` will be removed in the next release as we moved from `flask` to `fastapi`, so this error should not be raised after that.
See #701
