### ISSUE TITLE
Invalid user credentials after some cca 50 mins of ongoing download (cop_dataspace)

### ISSUE THREAD

**Issue by iliion** [CS-SI/eodag#803]
**Describe the bug**
I am able to download products from DATASPACE until an error is raised about Invalid user credentials after  ~50 mins of ongoing downloads.

**Output Error**

```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/srs_downloader/api/downloader.py", line 1068, in process_eodag_products
    geocoded_product = f.result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/venv/lib/python3.7/site-packages/srs_downloader/api/downloader.py", line 800, in process_single_eodag_product
    dag.download(eodag_eoproduct, outputs_prefix=scratch_dir)
  File "/opt/venv/lib/python3.7/site-packages/eodag/api/core.py", line 1812, in download
    progress_callback=progress_callback, wait=wait, timeout=timeout, **kwargs
  File "/opt/venv/lib/python3.7/site-packages/eodag/api/product/_product.py", line 305, in download
    if self.downloader_auth is not None
  File "/opt/venv/lib/python3.7/site-packages/eodag/plugins/authentication/keycloak.py", line 71, in authenticate
    % (e.response.status_code, e.response.text.strip(), self.provider)
eodag.utils.exceptions.AuthenticationError: HTTP Error 401 returned, {"error":"invalid_grant","error_description":"Invalid user credentials"}
Please check your credentials for cop_dataspace
```

Is it something I should take care of on my side? I am not sure but I though to report it anyway.

**Environment:**
 - Python version: `3.9.5`
 - EODAG version: `2.9.1`

**Comment by sbrunato** [comment]
Hello @iliion , I did not manage to reproduce this error.
Using eodag v2.9.1, I searched for `S2_MSI_L1C` products on `cop_dataspace`, then used `download_all` during around 1h30, without any error.
Do you still have this error ? If yes, can you give me more context on the search performed, and how you download the products ? 
Thanks

**Comment by iliion** [comment]
Hi @sbrunato . 
Might be because i use `download` (and not `download_all` ) to perform concurrent downloads? 

Adding here some more info from Dataspace rules and constraints:

For  "Copernicus Services" role. Therefore has the privileges that Copernicus Services offer, including "Number of concurrent connections limit (IAD): 20".

Consider the following:

- One token equals one session
- You don't need to generate a token for each product you want to download
- You should generate one token, use it to start downloading and if 10 minutes have passed, refresh the token and continue downloading again until 60 minutes have passed. At this point the token has to be regenerated.

**Comment by chiarch84** [comment]
Does EODAG handle the refresh token for Data Space within the 60 minutes time?

This is the code we are using:
```python
try:
        product_scratch_path = pathlib.Path(
            dag.download(eodag_eoproduct, outputs_prefix=scratch_dir)
        )
except AuthenticationError as e:
    logger.exception(e)
    dag = login_to_eodag_provider(provider=provider_name)
    process_single_eodag_product(
        product_uuid,
        base_path,
        collection_name,
        metadata,
        product_type,
        elastic,
        provider_name,
        eodag_eoproduct,
        dag,
        )
```

**Comment by sbrunato** [comment]
duplicate with #858
