### ISSUE TITLE
STAC filter extension

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#848]
From https://github.com/stac-api-extensions/query
> It is recommended to implement the [Filter Extension](https://github.com/stac-api-extensions/filter) instead of the Query Extension.

Do not begin to implement all the functionalities but only the already supported ones for the moment

**Comment by alambare-csgroup** [comment]
Pygeofilter is a python parser for CQL. We could use it to implement the AST tree parser.

> https://github.com/geopython/pygeofilter

**Comment by sbrunato** [comment]
Implemented with #966
