### ISSUE TITLE
external enhanced product types metadata

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#854]
Implement a mechanism to allow extending product types metadata using external json files.

Optionally add per product type in `product_types.yml` the path to a json file (local or remote).
Use `search.discover_product_types.generic_product_type_parsable_metadata` from `eodag/resources/stac_provider.yml` to extract product types properties in client mode.
In server mode, use client mode product types properties, overridden with external json file content.

**Comment by alambare-csgroup** [comment]
@sbrunato  Setting jsonpath per metadata sounds very complicated and very cumbersome. Maybe we could go with a more simple and straightforward implementation.
