### ISSUE TITLE
Add cruncher to search interface

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#86]
**[Original report](https://bitbucket.org/geostorm/eodag/issue/86) by Mickaël Savinaud (Bitbucket: [savmickael](https://bitbucket.org/savmickael), GitHub: [savmickael](https://github.com/savmickael)).**

----------------------------------------

It could be nice to add a cruncher to the search interface to avoid to do a two step filtering

**Comment by CGuichard** [comment]
Crunchers were added to SearchResult in #359. Thanks to this, calls to the crunchers have been simplified, and adding it to the search interface would add more means than necessary to achieve the same result.
