### ISSUE TITLE
Issue on page /notebooks/tutos/tuto_search_location_tile.html

### ISSUE THREAD

**Issue by YUEWONHUI** [CS-SI/eodag#897]
Hello, when I downloaded sentinel-L1C data in cop_dataspace using EODAGA, some images were downloaded as xxx.safe.zip, but some were downloaded as XXX.SAFE, and these files became unavailable when I manually added the.zip suffix to.safe. How can I make all downloads in XXX.SAFE.zip format?
![image](https://github.com/CS-SI/eodag/assets/142367674/0c9054ba-44e7-4d42-b6a9-b9fc0fe86c39)
![image](https://github.com/CS-SI/eodag/assets/142367674/3c868c30-c7d2-4c93-8386-9b8dcfd65de1)

**Comment by sbrunato** [comment]
Hello @YUEWONHUI and thanks for submitting this issue. 
If you check the logs, after having downloaded each file without zip extension, you should see a message like
```
2023-11-06 14:12:00,371 eodag.plugins.download.http      [WARNING ] (http             ) Downloaded product is not a Zip File. Please check its file type before using it
```
These files have a problem on Copernicus Dataspace side, and seem incomplete or corrupted.
EODAG removes the extension after downloading them to show that they are not zipfiles.
I also tried to download one of these files from https://dataspace.copernicus.eu/browser and also got an issue: download restarts when reaching 99% and finally fails later with a 401 error.

You can try to download these corrupted files from another provider.
