### ISSUE TITLE
hint client of download filename

### ISSUE THREAD

**Issue by alambare-csgroup** [CS-SI/eodag#937]
**Is your feature request related to a problem? Please describe.**

Currently EODAG server does not give the filename when downloading data.

For example, the following command will download and name it "download".
```console
wget http://localhost:8000/collections/S1_SAR_GRD/items/S1A_IW_GRDH_1SDV_20230831T234123_20230831T234152_050126_060852_FA06/download"
```

**Describe the solution you'd like**

Add the "Content-Disposition" header in download request response to hint the client of the filename.

```
Content-Disposition: attachment; filename="S1A_IW_GRDH_1SDV_20230831T234123_20230831T234152_050126_060852_FA06.zip"
```

**Describe alternatives you've considered**

We could also update URLs to look like the following instead. Or we could do both (header + URL).

```
http://localhost:8000/collections/S1_SAR_GRD/items/S1A_IW_GRDH_1SDV_20230831T234123_20230831T234152_050126_060852_FA06/download/S1A_IW_GRDH_1SDV_20230831T234123_20230831T234152_050126_060852_FA06.zip"
```

**Additional context**
Add any other context about the feature request here.

**Comment by sbrunato** [comment]
The "Content-Disposition" header is already used, but not implemented for all the download plugins. We should make sure it is
