### ISSUE TITLE
wrong provider name missing in queryables error message

### ISSUE THREAD

**Issue by alambare-csgroup** [CS-SI/eodag#938]
**Describe the bug**
When trying to filter queryables with a wrong provider, it's name is not returned in the error message.

![image](https://github.com/CS-SI/eodag/assets/90461111/0555b906-1a40-4694-880f-783862c15525)

**Code To Reproduce**
```sh
eodag serve-rest

curl http://127.0.0.1:5000/collections/S1_SAR_GRD/queryables?provider=qsdqd
```

**Comment by sbrunato** [comment]
already fixed
