### ISSUE TITLE
Bad URL on wekeo provider

### ISSUE THREAD

**Issue by ansotoo** [CS-SI/eodag#972]
**Describe the bug**
An error occurs when requesting wekeo provider

**Code To Reproduce**
```py
auth = dag._plugins_manager.get_auth_plugin("wekeo").authenticate()
```

**Output**
```
AuthenticationError: Could no get authentication token: HTTPSConnectionPool(host='wekeo-broker.apps.mercator.dpi.wekeo.eu', port=443): Max retries exceeded with url: /databroker/gettoken (Caused by ResponseError('too many 502 error responses')), 
```

**Environment:**
 - Python 3.11.0
 - eodag (Earth Observation Data Access Gateway): version 2.11.0

**Bugfix**
The wekeo url has changed : changing url from 'https://wekeo-broker.apps.mercator.dpi.wekeo.eu/databroker/' to 'https://wekeo-broker.prod.wekeo2.eu/databroker' in the provider configuration fixes the bug.

**Comment by sbrunato** [comment]
hello @ansotoo and thanks for submitting this issue

**Comment by sbrunato** [comment]
> Bugfix
The wekeo url has changed : changing url from 'https://wekeo-broker.apps.mercator.dpi.wekeo.eu/databroker/' to 'https://wekeo-broker.prod.wekeo2.eu/databroker' in the provider configuration fixes the bug.

this url did not last long. Instead, `wekeo` moved to a new API, see https://github.com/CS-SI/eodag/issues/999
