### ISSUE TITLE
problems with earth_search_cog

### ISSUE THREAD

**Issue by carolpitillas** [CS-SI/eodag#979]
Hello 
I need to download Sentinel 2 images from earth_search_cog repository. I need the images for the period January 2023 to December 2023 but I only can find available images from January to April. 
Is there any way to get the images from January 2023 to December 2023?

**Comment by sbrunato** [comment]
Hello @carolpitillas , this provider api endpoint moved from v0 to v1 and we need to adapt its configuration. Some work is already in progress but needs to be finished, see https://github.com/CS-SI/eodag/issues/735. We will let you know when it is done
