### ISSUE TITLE
Support downloaded products check from different providers.

### ISSUE THREAD

**Issue by Choumingzhao** [CS-SI/eodag#994]
**Is your feature request related to a problem? Please describe.**
According to this line in the code, the hash for downloaded product is calculated from the url of the product.
 https://github.com/CS-SI/eodag/blob/819247c9c57389db3b51d3d402b09edc5938ad53/eodag/plugins/download/base.py#L249C15-L249C15
 So when I download exact same product from two different providers, their hashes are different.  This feature cause the overwriting and re-downloading of exsiting downloaded product from another product. And this may be easily influenced by the url changes of provider websites.

**Describe the solution you'd like**
I think it would be better that the hash is calculated by consistent unique identifier (e.g. product.properties['id']) rather the url of the product.

**Comment by sbrunato** [comment]
Hello @Choumingzhao and many thanks for this feature request.
To avoid re-downloading same products from different providers, we can build hashes from `product_type + id` instead of their `remote_location`
